### ISSUE TITLE
Latest build broke our invocations to  Google.Cloud.Firestore... linking issue?

### ISSUE THREAD

**Issue by Imogynn** [dotnet/dotnet-docker#1306]
We are working on a website that uses Firestore for data access. It looks like some dependencies are no longer working in the latest container build. Everything was working fine yesterday morning but late yesterday and today we have had issues with Firestore not being available. It looks like something changed in the libraries in the container.

The start of our docker setup:

```
FROM microsoft/dotnet:2.2-sdk-alpine as builder
RUN apk update && apk add libc6-compat
```

The code in our controller:
```

public XController(...)
        {
...
            try {
                db = FirestoreDb.Create(_fbSettings.ProjectId);
            } catch (Exception ex)
            {
                _log.Error("X CONTROLLER - Could not connect to firestore! Endpoints may be flakey.");
                _log.Error("X CONTROLLER - Exception: " + ex.ToString());
            }
...
        }

```

We are catching a a new exception off the call to FirestoreDb.Create():

```
Exception: System.IO.IOException: Error loading native library "/app/runtimes/linux/native/libgrpc_csharp_ext.x64.so"
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Google.Api.Gax.Grpc.ChannelPool.GetChannel(ServiceEndpoint endpoint, ChannelCredentials credentials)
   at Google.Cloud.Firestore.FirestoreDb.Create(String projectId, String databaseId, FirestoreClient client)

```
For what it's worth the file in question (libgrpc_csharp_ext.x64.so) is in the right place, but we're not sure the dependencies aren't correct for it:
```

/app/runtimes/linux/native # ldd libgrpc_csharp_ext.x64.so 
    ldd (0x7fb110296000)
    libdl.so.2 => ldd (0x7fb110296000)
    librt.so.1 => ldd (0x7fb110296000)
    libm.so.6 => ldd (0x7fb110296000)
    libpthread.so.0 => ldd (0x7fb110296000)
    libc.so.6 => ldd (0x7fb110296000)
```

Not sure we aren't missing a step but as I said it was working yesterday, and stopped working pretty much when you released your new build. If you have any insight, we'd appreciate it. 

Maybe there's a way to use yesterday's image to verify, but we didn't find an immediate way to use the older container.

Thanks

**Comment by MichaelSimons** [comment]
Closing per @mthalman's assessment of a missing dependency required in Alpine 3.9.
