### ISSUE TITLE
Cannot consume scoped service | IHostedService

### ISSUE THREAD

**Issue by seanmt13** [dotnet/dotnet-docker#1327]
## Steps to reproduce the issue
I am using an IHostedService to run a background task in my asp.net core web application. I can publish and run my app locally and it works.

`dotnet publish ./MyWebApp`
`dotnet myApp.dll`

 I can even build the docker image using either the linux container or windows container 
`FROM mcr.microsoft.com/dotnet/core/aspnet:2.2`

As soon as I try to run the docker image built using the IHostedService it fails. 

` System.InvalidOperationException: Cannot consume scoped service 'MyNameSpace.IMyRepo' from singleton 'MyNameSpace.IMyRepo'.`

DockerFile Entrypoint Linux Container
`ENTRYPOINT /bin/bash -c "dotnet Lds.CM.MT.Web.dll --launch-profile Development"`

DockerFile Entrypoint Windows Container
`ENTRYPOINT ["dotnet", "Lds.CM.MT.Web.dll"]`

## Expected behavior
I would expect the image to run the same as when i publish and run locally. 

## Actual behavior
It appears that something in the mcr.microsoft.com/dotnet/core/aspnet:2.2 image is causing issues when using dependency injection with a IHostedService. As I can publish and run the application locally outside of docker. 

## Additional information
Below is my IHostedService implementation. Note this image was working until I added the IHostedService. If i comment out my dependency injection in this file the docker image will run just fine. 
```
internal class TimedHostedService : IHostedService, IDisposable
{
    private readonly ILogger _logger;
    public IServiceScopeFactory _serviceScopeFactory;
    private readonly IMyRepo _myRep;
    private Timer _timer;

    public TimedHostedService(ILogger<TimedHostedService> logger, IServiceScopeFactory serviceScopeFactory)
    {
        _logger = logger;
        try
        {
            _serviceScopeFactory = serviceScopeFactory;
            _logger.LogInformation("Got serviceFactory");
            using (var scope = _serviceScopeFactory.CreateScope())
            {
                _logger.LogInformation("created scope");
                _myRepo = scope.ServiceProvider.GetRequiredService<IMyRepo>();
                _logger.LogInformation("got instance");
            }
        }
        catch (Exception e)
        {
            _logger.LogError("timedhostedservice", e);
            throw;
        }
     
    }

    public Task StartAsync(CancellationToken cancellationToken)
    {
        _logger.LogInformation("Timed Background Service is starting.");

        _timer = new Timer(DoWork, null, TimeSpan.Zero,
            TimeSpan.FromSeconds(60));

        return Task.CompletedTask;
    }

    private void DoWork(object state)
    {
        _logger.LogInformation("Timed Background Service is working.");
        _myRepo.ReadMessages().Wait();
    }

    public Task StopAsync(CancellationToken cancellationToken)
    {
        _logger.LogInformation("Timed Background Service is stopping.");

        _timer?.Change(Timeout.Infinite, 0);

        return Task.CompletedTask;
    }

    public void Dispose()
    {
        _timer?.Dispose();
    }
}
```

## Output of `docker version`

```
Docker version 19.03.2, build 6a30dfc
```

## Output of `docker info`

```
Unhandled Exception: System.InvalidOperationException: Cannot consume scoped service 'MyNameSpace.IMyRepo' from singleton 'MyNameSpace.IMyRepo''.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitScoped(ScopedCallSite scopedCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitConstructor(ConstructorCallSite constructorCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitSingleton(SingletonCallSite singletonCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitConstructor(ConstructorCallSite constructorCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitSingleton(SingletonCallSite singletonCallSite, CallSiteValidatorState state)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateCallSite(IServiceCallSite callSite)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback.OnCreate(IServiceCallSite callSite)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at TimedHostedService..ctor(ILogger`1 logger, IServiceScopeFactory serviceScopeFactory) in C:\Users\seanmt13\source\repos\mediatoolsrewrite\Lds.CM.MT.Web\TimedHostedService.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by MichaelSimons** [comment]
@seanmt13 - can you please provide a set of steps that can be used to reproduce the problem?

**Comment by MichaelSimons** [comment]
Closing due to inactivity.

**Comment by edencorbin** [comment]
I believe I am having the same issue, it logs locally just fine but on a deployed Azure docker container, the hosted service does not seem to be entering / logging.
