### ISSUE TITLE
Investigate cause of build agent issues in 1903 scale set

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1561]
The build agents in this scale set have been consistently encountering errors like below.  Reboot doesn't resolve the issue.

```
Step 1/12 : FROM mcr.microsoft.com/windows/servercore:1903 AS installer
 ---> 8132c4e442c3
Step 2/12 : SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
 ---> Using cache
 ---> 4d22c2233b21
Step 3/12 : RUN $dotnet_sdk_version = '3.1.100';     Invoke-WebRequest -OutFile dotnet.zip https://dotnetcli.azureedge.net/dotnet/Sdk/$dotnet_sdk_version/dotnet-sdk-$dotnet_sdk_version-win-x64.zip;     $dotnet_sha512 = '94ee575d6104058cdd31370fc686b5d1aa23bf4a54611843c1f93afc82cad3523217b5f2eaddd4b5c136bca252d2c9047092f7054052c8683fa0f363ca28ad11';     if ((Get-FileHash dotnet.zip -Algorithm sha512).Hash -ne $dotnet_sha512) {         Write-Host 'CHECKSUM VERIFICATION FAILED!';         exit 1;     };         Expand-Archive dotnet.zip -DestinationPath dotnet;     Remove-Item -Force dotnet.zip
 ---> Running in 66e4bc11a96f
hcsshim::PrepareLayer - failed failed in Win32: The specified network resource or device is no longer available. (0x37)
Retry 3/5, retrying in 25 seconds...
Sending build context to Docker daemon  4.608kB

Step 1/12 : FROM mcr.microsoft.com/windows/servercore:1903 AS installer
 ---> 8132c4e442c3
Step 2/12 : SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
 ---> Using cache
 ---> 4d22c2233b21
Step 3/12 : RUN $dotnet_sdk_version = '3.1.100';     Invoke-WebRequest -OutFile dotnet.zip https://dotnetcli.azureedge.net/dotnet/Sdk/$dotnet_sdk_version/dotnet-sdk-$dotnet_sdk_version-win-x64.zip;     $dotnet_sha512 = '94ee575d6104058cdd31370fc686b5d1aa23bf4a54611843c1f93afc82cad3523217b5f2eaddd4b5c136bca252d2c9047092f7054052c8683fa0f363ca28ad11';     if ((Get-FileHash dotnet.zip -Algorithm sha512).Hash -ne $dotnet_sha512) {         Write-Host 'CHECKSUM VERIFICATION FAILED!';         exit 1;     };         Expand-Archive dotnet.zip -DestinationPath dotnet;     Remove-Item -Force dotnet.zip
 ---> Running in 954a5ba98f90
hcsshim::PrepareLayer - failed failed in Win32: The physical end of the tape has been reached. (0x44c)
Retry 4/5, retrying in 125 seconds...
Sending build context to Docker daemon  4.608kB

Step 1/12 : FROM mcr.microsoft.com/windows/servercore:1903 AS installer
 ---> 8132c4e442c3
Step 2/12 : SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
 ---> Using cache
 ---> 4d22c2233b21
Step 3/12 : RUN $dotnet_sdk_version = '3.1.100';     Invoke-WebRequest -OutFile dotnet.zip https://dotnetcli.azureedge.net/dotnet/Sdk/$dotnet_sdk_version/dotnet-sdk-$dotnet_sdk_version-win-x64.zip;     $dotnet_sha512 = '94ee575d6104058cdd31370fc686b5d1aa23bf4a54611843c1f93afc82cad3523217b5f2eaddd4b5c136bca252d2c9047092f7054052c8683fa0f363ca28ad11';     if ((Get-FileHash dotnet.zip -Algorithm sha512).Hash -ne $dotnet_sha512) {         Write-Host 'CHECKSUM VERIFICATION FAILED!';         exit 1;     };         Expand-Archive dotnet.zip -DestinationPath dotnet;     Remove-Item -Force dotnet.zip
 ---> Running in f8f73daef002
hcsshim::PrepareLayer - failed failed in Win32: The specified network resource or device is no longer available. (0x37)
-- EXECUTION ELAPSED TIME: 00:05:14.3012172
System.InvalidOperationException: Failed to execute docker build -t mcr.microsoft.com/dotnet/core-nightly/sdk:3.1.100-nanoserver-1903 -t mcr.microsoft.com/dotnet/core-nightly/sdk:3.1-nanoserver-1903 -t mcr.microsoft.com/dotnet/core-nightly/sdk:3.1.100 -t mcr.microsoft.com/dotnet/core-nightly/sdk:3.1 -t mcr.microsoft.com/dotnet/core-nightly/sdk:latest -f 3.1/sdk/nanoserver-1903/amd64/Dockerfile 3.1/sdk/nanoserver-1903/amd64
   at Microsoft.DotNet.ImageBuilder.ExecuteHelper.Execute(ProcessStartInfo info, Func`2 executor, Boolean isDryRun, String errorMessage, String executeMessageOverride) in C:\image-builder\src\ExecuteHelper.cs:line 80
   at Microsoft.DotNet.ImageBuilder.ExecuteHelper.ExecuteWithRetry(String fileName, String args, Boolean isDryRun, String errorMessage, String executeMessageOverride) in C:\image-builder\src\ExecuteHelper.cs:line 46
   at Microsoft.DotNet.ImageBuilder.DockerService.BuildImage(String dockerfilePath, String buildContextPath, IEnumerable`1 tags, IDictionary`2 buildArgs, Boolean isRetryEnabled, Boolean isDryRun) in C:\image-builder\src\DockerService.cs:line 51
   at Microsoft.DotNet.ImageBuilder.Commands.BuildCommand.BuildImages() in C:\image-builder\src\Commands\BuildCommand.cs:line 87
   at Microsoft.DotNet.ImageBuilder.Commands.BuildCommand.ExecuteAsync() in C:\image-builder\src\Commands\BuildCommand.cs:line 40
   at Microsoft.DotNet.ImageBuilder.ImageBuilder.Main(String[] args) in C:\image-builder\src\ImageBuilder.cs:line 66
```

**Comment by mthalman** [comment]
While I don't think this is the cause of the issue, I did find that old Windows images were not being cleaned up: https://github.com/dotnet/docker-tools/issues/369

**Comment by MichaelSimons** [comment]
@mthalman, Can you update this issue with the findings?  IIRC you stated the Docker data drive was not configured correctly.  Is there an issue tracking this or has DDFUN already addressed the problem?

**Comment by mthalman** [comment]
This was due to lack of disk space on the disk where the Docker images were stored.  DDFUN has deployed a new VM image that provides a larger disk size.  Closing.
