### ISSUE TITLE
Tracking: Semaphore error when running "dotnet test" in Windows ARM container

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1608]
Tracking issue for bug: https://microsoft.visualstudio.com/OS/_workitems/edit/24672377 (internal MSFT link)

This error was discovered when running the `test` stage of the Dockerfile for the [complexapp sample](https://github.com/dotnet/dotnet-docker/tree/master/samples/complexapp) on Windows 1809 ARM:

```
Test run for C:\source\tests\bin\Debug\netcoreapp3.1\tests.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
Results File: C:\source\tests\TestResults\ContainerUser_72D739BC5122_2020-01-17_13_37_45.trx
Failed to launch testhost with error: System.AggregateException: One or more errors occurred. (Too many posts were made to a semaphore.)
 ---> System.ComponentModel.Win32Exception (298): Too many posts were made to a semaphore.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.ProcessHelper.LaunchProcess(String processPath, String arguments, String workingDirectory, IDictionary`2 envVariables, Action`2 errorCallback, Action`1 exitCallBack)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.LaunchHost(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.<>c__DisplayClass36_0.<LaunchTestHostAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.LaunchTestHostAsync(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
Test Run Aborted.
```

**Comment by mthalman** [comment]
Once this issue is resolved, the testing should be renamed for Windows ARM here:

https://github.com/dotnet/dotnet-docker/blob/663778f551abac5c50bd18bab19d3cc72755905b/tests/Microsoft.DotNet.Docker.Tests/SampleImageTests.cs#L98

**Comment by mthalman** [comment]
The Windows issue has been closed in favor of a .NET runtime issue that we're now tracking: https://github.com/dotnet/runtime/issues/2082.

**Comment by MichaelSimons** [comment]
Closing since support for Windows ARM is being dropped (#1840).
