### ISSUE TITLE
libuv is not included

### ISSUE THREAD

**Issue by colemickens** [dotnet/dotnet-docker#17]
`dpkg -l | grep uv` returns no results. When I try to run these https://github.com/davidfowl/dotnetcli-aspnet5 examples in the container I get this:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.DllNotFoundException: Unable to load DLL 'libuv': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.NativeMethods.uv_loop_size()
   at Microsoft.AspNet.Server.Kestrel.Networking.UvLoopHandle.Init(Libuv uv)
   at Microsoft.AspNet.Server.Kestrel.KestrelThread.ThreadStart(Object parameter)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNet.Server.Kestrel.KestrelEngine.Start(Int32 count)
   at Microsoft.AspNet.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.Start()
   at Microsoft.AspNet.Hosting.WebApplication.Run(Type startupType, String[] args)
   at HelloMvc.Startup.Main(String[] args)
```

**Comment by ahmetalpbalkan** [comment]
@colemickens hmm I think microsoft/aspnet docker image is the right place to do that. It installs libuv although it doesn't use this new dotnet docker image, soon it will.

**Comment by colemickens** [comment]
I think I agree, since libuv is just required by Kestrel.
