### ISSUE TITLE
Portable Git submodule command not working in NanoServer

### ISSUE THREAD

**Issue by johnysmith55** [dotnet/dotnet-docker#1809]
I've explained the bug here: https://stackoverflow.com/questions/61019804/npm-submodule-command-not-working-in-nanoserver-in-docker

**Comment by MichaelSimons** [comment]
This question appears specific to Windows containers (Nano Server) and does not appear to be related to the .NET Core docker images.  Please post this to the [windows containers forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers).

**Comment by johnysmith55** [comment]
@MichaelSimons It's the mcr.microsoft.com/dotnet/core/sdk:3.1.101-nanoserver-1909 image. Isn't this a .NET Core Image with Nano Server?

**Comment by MichaelSimons** [comment]
@johnysmith55 - your problem appears to be related to NPM + git + Nano Server.  Try removing the .NET sdk image from your repo to boil the problem down.  Please try your repro steps with just the mcr.microsoft.com/windows/nanoserver:1909 image.

**Comment by johnysmith55** [comment]
@MichaelSimons Just tried with the mcr.microsoft.com/windows/nanoserver:1909 image. Got the same result. Here is the Dockerfile: 

```
# escape=`
# Args used by from statements must be defined here:
ARG fromTag=1709
ARG InstallerVersion=nanoserver
ARG InstallerRepo=mcr.microsoft.com/powershell
ARG NanoServerRepo=mcr.microsoft.com/windows/nanoserver

# Use server core as an installer container to extract PowerShell,
# As this is a multi-stage build, this stage will eventually be thrown away
FROM ${InstallerRepo}:$InstallerVersion  AS powershell-installer-env

# Arguments for installing PowerShell, must be defined in the container they are used
ARG PS_VERSION=7.0.0

ARG PS_PACKAGE_URL=https://github.com/PowerShell/PowerShell/releases/download/v$PS_VERSION/PowerShell-$PS_VERSION-win-x64.zip

SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ARG PS_PACKAGE_URL_BASE64

RUN Write-host "Verifying valid Version..."; `
    if (!($env:PS_VERSION -match '^\d+\.\d+\.\d+(-\w+(\.\d+)?)?$' )) { `
        throw ('PS_Version ({0}) must match the regex "^\d+\.\d+\.\d+(-\w+(\.\d+)?)?$"' -f $env:PS_VERSION) `
    } `
    $ProgressPreference = 'SilentlyContinue'; `
    if($env:PS_PACKAGE_URL_BASE64){ `
        Write-host "decoding: $env:PS_PACKAGE_URL_BASE64" ;`
        $url = [System.Text.Encoding]::Unicode.GetString([System.Convert]::FromBase64String($env:PS_PACKAGE_URL_BASE64)) `
    } else { `
        Write-host "using url: $env:PS_PACKAGE_URL" ;`
        $url = $env:PS_PACKAGE_URL `
    } `
    Write-host "downloading: $url"; `
    [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12; `
    New-Item -ItemType Directory /installer > $null ; `
    Invoke-WebRequest -Uri $url -outfile /installer/powershell.zip -verbose; `
    Expand-Archive /installer/powershell.zip -DestinationPath \PowerShell

FROM mcr.microsoft.com/windows/servercore:ltsc2019 AS git-installer

RUN setx /M Path "%Path%;C:\7zip"

RUN powershell -command Invoke-WebRequest -outfile portableGit.7z.exe https://github.com/git-for-windows/git/releases/download/v2.26.0.windows.1/PortableGit-2.26.0-64-bit.7z.exe
RUN powershell -command Invoke-WebRequest -UserAgent 'DockerCI' -outfile 7zsetup.exe http://www.7-zip.org/a/7z1514-x64.exe
RUN powershell -command start-process .\7zsetup.exe -ArgumentList '/S /D=C:/7zip' -Wait

RUN powershell 7z x portableGit.7z.exe -ogit

FROM mcr.microsoft.com/windows/nanoserver:1909
#~Installing Powershell
ARG VCS_REF="none"
ARG PS_VERSION=7.0.0
ARG IMAGE_NAME=mcr.microsoft.com/powershell

# Copy PowerShell Core from the installer container
ENV ProgramFiles="C:\Program Files" `
    # set a fixed location for the Module analysis cache
    LOCALAPPDATA="C:\Users\ContainerAdministrator\AppData\Local" `
    PSModuleAnalysisCachePath="$LOCALAPPDATA\Microsoft\Windows\PowerShell\docker\ModuleAnalysisCache" `
    # Persist %PSCORE% ENV variable for user convenience
    PSCORE="$ProgramFiles\PowerShell\pwsh.exe" `
    # Set the default windows path so we can use it
    WindowsPATH="C:\Windows\system32;C:\Windows" `
    POWERSHELL_DISTRIBUTION_CHANNEL="PSDocker-NanoServer-${fromTag}"

### Begin workaround ###
# Note that changing user on nanoserver is not recommended
# See, https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-base-images#base-image-differences
# But we are working around a bug introduced in the nanoserver image introduced in 1809
# Without this, PowerShell Direct will fail
# this command sholud be like this: https://github.com/PowerShell/PowerShell-Docker/blob/f81009c42c96af46aef81eb1515efae0ef29ad5f/release/preview/nanoserver/docker/Dockerfile#L76
USER ContainerAdministrator

# This is basically the correct code except for the /M
RUN setx PATH "%PATH%;%ProgramFiles%\PowerShell;" /M

USER ContainerUser
### End workaround ###

COPY --from=powershell-installer-env ["\\PowerShell\\", "$ProgramFiles\\PowerShell"]

# intialize powershell module cache
RUN pwsh `
        -NoLogo `
        -NoProfile `
        -Command " `
          $stopTime = (get-date).AddMinutes(15); `
          $ErrorActionPreference = 'Stop' ; `
          $ProgressPreference = 'SilentlyContinue' ; `
          while(!(Test-Path -Path $env:PSModuleAnalysisCachePath)) {  `
            Write-Host "'Waiting for $env:PSModuleAnalysisCachePath'" ; `
            if((get-date) -gt $stopTime) { throw 'timout expired'} `
            Start-Sleep -Seconds 6 ; `
          }"

LABEL maintainer="PowerShell Team <powershellteam@hotmail.com>" `
      readme.md="https://github.com/PowerShell/PowerShell/blob/master/docker/README.md" `
      description="This Dockerfile will install the latest release of PowerShell." `
      org.label-schema.usage="https://github.com/PowerShell/PowerShell/tree/master/docker#run-the-docker-image-you-built" `
      org.label-schema.url="https://github.com/PowerShell/PowerShell/blob/master/docker/README.md" `
      org.label-schema.vcs-url="https://github.com/PowerShell/PowerShell-Docker" `
      org.label-schema.name="powershell" `
      org.label-schema.vcs-ref=${VCS_REF} `
      org.label-schema.vendor="PowerShell" `
      org.label-schema.version=${PS_VERSION} `
      org.label-schema.schema-version="1.0" `
      org.label-schema.docker.cmd="docker run ${IMAGE_NAME} pwsh -c '$psversiontable'" `
      org.label-schema.docker.cmd.devel="docker run ${IMAGE_NAME}" `
      org.label-schema.docker.cmd.test="docker run ${IMAGE_NAME} pwsh -c Invoke-Pester" `
      org.label-schema.docker.cmd.help="docker run ${IMAGE_NAME} pwsh -c Get-Help"
#Installing powershell~

USER ContainerAdministrator
RUN setx /M Path "C:\git\bin;C:\git\usr\bin;C:\git\mingw64\bin;C:\nodejs;%Path%"
COPY --from=git-installer "C:\git" "C:\git"
COPY WebApplication11/package.json package.json
COPY WebApplication11/package-lock.json package-lock.json

RUN pwsh -command Invoke-WebRequest -OutFile "nodejs.zip" "https://nodejs.org/dist/v13.9.0/node-v13.9.0-win-x64.zip"
RUN pwsh -command Expand-Archive "nodejs.zip" -DestinationPath "C:/"
RUN pwsh -command Rename-Item "C:/node-v13.9.0-win-x64" "C:/nodejs"
```

Here is the npm log: 

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\nodejs\\node.exe',
1 verbose cli   'C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install'
1 verbose cli ]
2 info using npm@6.13.7
3 info using node@v13.9.0
4 verbose npm-session 8e0ec257d83916b2
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall webapplication11@1.0.0
7 info lifecycle webapplication11@1.0.0~preinstall: webapplication11@1.0.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 15ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 0ms
16 silly install loadAllDepsIntoIdealTree
17 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 16ms
18 timing stage:loadIdealTree Completed in 16ms
19 silly currentTree webapplication11@1.0.0
20 silly idealTree webapplication11@1.0.0
20 silly idealTree +-- jquery-comments@git+https://github.com/Viima/jquery-comments.git#168ebf66ca33f16aab672dd5072503bd4333737a
20 silly idealTree `-- jquery@3.4.1
21 silly install generateActionsToTake
22 timing stage:generateActionsToTake Completed in 0ms
23 silly diffTrees action count 2
24 silly diffTrees add jquery@3.4.1
25 silly diffTrees add jquery-comments@git+https://github.com/Viima/jquery-comments.git#168ebf66ca33f16aab672dd5072503bd4333737a
26 silly decomposeActions action count 16
27 silly decomposeActions fetch jquery@3.4.1
28 silly decomposeActions extract jquery@3.4.1
29 silly decomposeActions preinstall jquery@3.4.1
30 silly decomposeActions build jquery@3.4.1
31 silly decomposeActions install jquery@3.4.1
32 silly decomposeActions postinstall jquery@3.4.1
33 silly decomposeActions finalize jquery@3.4.1
34 silly decomposeActions refresh-package-json jquery@3.4.1
35 silly decomposeActions fetch jquery-comments@git+https://github.com/Viima/jquery-comments.git#168ebf66ca33f16aab672dd5072503bd4333737a
36 silly decomposeActions extract jquery-comments@git+https://github.com/Viima/jquery-comments.git#168ebf66ca33f16aab672dd5072503bd4333737a
37 silly decomposeActions preinstall jquery-comments@git+https://github.com/Viima/jquery-comments.git#168ebf66ca33f16aab672dd5072503bd4333737a
38 silly decomposeActions build jquery-comments@git+https://github.com/Viima/jquery-comments.git#168ebf66ca33f16aab672dd5072503bd4333737a
39 silly decomposeActions install jquery-comments@git+https://github.com/Viima/jquery-comments.git#168ebf66ca33f16aab672dd5072503bd4333737a
40 silly decomposeActions postinstall jquery-comments@git+https://github.com/Viima/jquery-comments.git#168ebf66ca33f16aab672dd5072503bd4333737a
41 silly decomposeActions finalize jquery-comments@git+https://github.com/Viima/jquery-comments.git#168ebf66ca33f16aab672dd5072503bd4333737a
42 silly decomposeActions refresh-package-json jquery-comments@git+https://github.com/Viima/jquery-comments.git#168ebf66ca33f16aab672dd5072503bd4333737a
43 silly install executeActions
44 silly doSerial global-install 16
45 verbose correctMkdir C:\Users\ContainerAdministrator\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
46 verbose makeCacheDir UID & GID are irrelevant on win32
47 verbose lock using C:\Users\ContainerAdministrator\AppData\Roaming\npm-cache\_locks\staging-45ac2948c771167d.lock for C:\node_modules\.staging
48 silly doParallel extract 2
49 silly extract jquery@3.4.1
50 silly extract jquery-comments@git+https://github.com/Viima/jquery-comments.git#168ebf66ca33f16aab672dd5072503bd4333737a
51 silly tarball trying jquery@3.4.1 by hash: sha512-36+AdBzCL+y6qjw5Tx7HgzeGCzC81MDDgaUP8ld2zhx58HdqXGoBd+tHdrBMiyjGQs0Hxs/MLZTu/eHNJJuWPw==
52 silly tarball no local data for git+https://github.com/Viima/jquery-comments.git#168ebf66ca33f16aab672dd5072503bd4333737a. Extracting by manifest.
53 silly tarball no local data for jquery@3.4.1. Extracting by manifest.
54 http fetch GET 200 https://registry.npmjs.org/jquery/-/jquery-3.4.1.tgz 172ms
55 silly extract jquery@3.4.1 extracted to C:\node_modules\.staging\jquery-542ca737 (313ms)
56 timing audit submit Completed in 555ms
57 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 555ms
58 timing audit body Completed in 0ms
59 timing action:extract Completed in 39428ms
60 verbose unlock done using C:\Users\ContainerAdministrator\AppData\Roaming\npm-cache\_locks\staging-45ac2948c771167d.lock for C:\node_modules\.staging
61 timing stage:rollbackFailedOptional Completed in 0ms
62 timing stage:runTopLevelLifecycles Completed in 39679ms
63 silly saveTree webapplication11@1.0.0
63 silly saveTree `-- jquery-comments@git+https://github.com/Viima/jquery-comments.git#168ebf66ca33f16aab672dd5072503bd4333737a
63 silly saveTree   `-- jquery@3.4.1
64 warn webapplication11@1.0.0 No description
65 warn webapplication11@1.0.0 No repository field.
66 verbose stack Error: Command failed: git submodule update -q --init --recursive
66 verbose stack
66 verbose stack     at ChildProcess.exithandler (child_process.js:303:12)
66 verbose stack     at ChildProcess.emit (events.js:321:20)
66 verbose stack     at maybeClose (internal/child_process.js:1026:16)
66 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
67 verbose cwd C:\
68 verbose Windows_NT 10.0.18363
69 verbose argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
70 verbose node v13.9.0
71 verbose npm  v6.13.7
72 error code 57
73 error Command failed: git submodule update -q --init --recursive
74 verbose exit [ 1, true ]
```

The package.json and package-lock.json are the same. Had to use the PowerShell Docker file from here: https://github.com/PowerShell/PowerShell-Docker/blob/master/release/stable/nanoserver1809/docker/Dockerfile to download it in the NanoServer image, since it seems that it doesn't have it.
