### ISSUE TITLE
OutOfMemory on dotnet new console

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-docker#1810]
I am seeing some odd behavior with the console template in docker. I am seeing similar behavior on multiple machines. Just me?

Here is what I'm seeing:

```console
C:\Users\rich>docker pull mcr.microsoft.com/dotnet/core/sdk:3.1
3.1: Pulling from dotnet/core/sdk
f15005b0235f: Already exists
41ebfd3d2fd0: Already exists
b998346ba308: Already exists
f01ec562c947: Already exists
de2914a3bce9: Pull complete
e1060ee932d6: Pull complete
b2ee07dee813: Pull complete
Digest: sha256:bf755bf00ee2712af5fb71af0aea57e8e65dc2cc191f28c2d1f95c325f00177f
Status: Downloaded newer image for mcr.microsoft.com/dotnet/core/sdk:3.1
mcr.microsoft.com/dotnet/core/sdk:3.1

C:\Users\rich>docker run --rm mcr.microsoft.com/dotnet/core/sdk:3.1 dotnet new console
Getting ready...
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /ConsoleApp1.csproj...

C:\Users\rich>docker run --rm mcr.microsoft.com/dotnet/core/sdk:3.1 dotnet new console
Getting ready...
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /ConsoleApp1.csproj...
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Microsoft.Build.BackEnd.BuildComponentFactoryCollection.ShutdownComponents()
   at Microsoft.Build.Execution.BuildManager.Dispose(Boolean disposing)
   at Microsoft.Build.Execution.BuildManager.Dispose()
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, String[] inputResultsCaches, String outputResultsCache)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
Out of memory.


Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'


C:\Users\rich>docker run --rm mcr.microsoft.com/dotnet/core/sdk:3.1 dotnet new console
Getting ready...
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /ConsoleApp1.csproj...
Out of memory.


Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'


C:\Users\rich>docker run -it --rm mcr.microsoft.com/dotnet/core/sdk:3.1
root@f9c988229827:/# dotnet new console
Getting ready...
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /ConsoleApp1.csproj...
Out of memory.


Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'

root@f9c988229827:/# dotnet new web
Creating this template will make changes to existing files:
  Overwrite   Program.cs

Rerun the command and pass --force to accept and create.
root@f9c988229827:/# dotnet new web -o web
The template "ASP.NET Core Empty" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on web/web.csproj...
  Restore completed in 126.72 ms for /web/web.csproj.

Restore succeeded.

root@f9c988229827:/# exit
exit

C:\Users\rich>docker run --rm mcr.microsoft.com/dotnet/core/sdk:3.1 dotnet new web
Getting ready...
The template "ASP.NET Core Empty" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /WebApplication.csproj...

```

**Comment by mthalman** [comment]
FWIW, I'm not seeing this behavior.  I can run the `new console` command repeatedly with success.  It seems like it's something screwy with Docker itself.  What version of Docker are you using?  Here's what I have:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by MichaelSimons** [comment]
I was able to reproduce this.  I suspect this is because you are operating at the root of the drive.  `dotnet restore` is walking the entire directory structure looking for projects to restore.  I recall there being a number of issues logged against the CLI in the past related to this.  Try specifying a working directory - `docker run --rm -w /app mcr.microsoft.com/dotnet/core/sdk:3.1 dotnet new console`.  If you can confirm, this issue should be moved to the sdk repo.

**Comment by richlander** [comment]
Problem solved. I recall this same problem in the past (and forgot about this behavioral reason).  Super annoying. Not worth fixing, but unintuitive.
