### ISSUE TITLE
update-dependencies fails when attempting to update existing PR

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1898]
The update-dependencies tool has special logic that handles a case where there's an existing PR.  This logic fails with the following error:

```
System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'git2-106a5f2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libgit2-106a5f2: cannot open shared object file: No such file or directory
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary()
   at LibGit2Sharp.Core.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at LibGit2Sharp.Core.NativeMethods.git_clone(git_repository*& repo, String origin_url, FilePath workdir_path, GitCloneOptions& opts)
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts)
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options)
   at Dotnet.Docker.Program.UpdateExistingPullRequest(GitHubAuth gitHubAuth, PullRequestOptions prOptions, String commitMessage, GitHubBranch upstreamBranch) in /update-dependencies/Program.cs:line 188
   at Dotnet.Docker.Program.CreatePullRequestAsync() in /update-dependencies/Program.cs:line 155
   at Dotnet.Docker.Program.Main(String[] args) in /update-dependencies/Program.cs:line 53
```

**Comment by omajid** [comment]
We have seen this problem when the version of `libgit2.so` isn't compatible with the platform, for some reason or another. For example, if the `x64` version is being loaded when the platform is `arm64`. What os/container is this code running in?

**Comment by omajid** [comment]
Some repos, like sourcelink, even migrated off of libgit2sharp because of portability issues: https://github.com/dotnet/sourcelink/pull/288

**Comment by mthalman** [comment]
Nothing too fancy going on.  The build job literally builds the [Dockerfile](https://github.com/dotnet/dotnet-docker/blob/master/eng/update-dependencies/Dockerfile) locally and runs it.  This runs on an AMD64 machine.

**Comment by MichaelSimons** [comment]
@mthalman can this issue be closed?  If not what work is remaining?
