### ISSUE TITLE
Missing package libldap-2.4.so.2 at runtime:5.0-buster-slim

### ISSUE THREAD

**Issue by brunohbrito** [dotnet/dotnet-docker#1946]
## Steps to reproduce the issue
1. Create a .NET 5.0 Console app
2. Run:
```ps1
dotnet new nugetconfig
dotnet nuget add source -n dotnet5 https://dnceng.pkgs.visualstudio.com/public/_packaging/dotnet5/nuget/v3/index.json
```
3. Get night build from System.DirectoryServices.Protocols, version 5.0.0-preview.6.20272.2
4. Add the following code: 
``` c#
var credential = new NetworkCredential("<username>", "<password>");
var connection = new LdapConnection(new LdapDirectoryIdentifier("<ip(13.0.0.0)>", 389, false, false), credential);
connection.Bind();
```
5. Run into container runtime:5.0-buster-slim
Reference Dockerfile
``` dockerfile
FROM mcr.microsoft.com/dotnet/core/runtime:5.0-buster-slim AS base
RUN apt-get update && apt-get install -y libldap-2.4-2
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:5.0-buster AS build
WORKDIR /src
COPY ["TesteLdap/TesteLdap.csproj", "TesteLdap/"]
COPY ["nuget.config", "/src"]
RUN dotnet restore "TesteLdap/TesteLdap.csproj" --configfile "nuget.config"
COPY . .
WORKDIR "/src/TesteLdap"
RUN dotnet build "TesteLdap.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TesteLdap.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TesteLdap.dll"]
```

## Expected behavior
Run without bugs

## Actual behavior
We got this error at logs: 
 `Unable to load shared library 'libldap-2.4.so.2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibldap-2.4.so.2: cannot open shared object file: No such file or directory`

## Additional information (e.g. issue happens only occasionally)

The next version of System.DirectoryServices.Protocols has a dependency of `libldap-2.4`.
related to:
* [dotnet/runtime issue 36948](https://github.com/dotnet/runtime/issues/36948) 
* [dotnet/runtime issue 36888](https://github.com/dotnet/runtime/issues/36888)
* [dotnet/runtime issue 36947](https://github.com/dotnet/runtime/issues/36947)

**Comment by MichaelSimons** [comment]
@brunohbrito - Thanks for bringing this to our attention.  There are a couple factors we consider when adding dependencies.

1. How widely used are the scenarios that require the dependencies?  The more generally the scenario, the more it makes sense to add the dependency.
2. What is the size impact of adding the dependencies?  In this case installing libldap-2.4.2 appears to add 1.64 MB to the buster-slim image.

**Comment by brunohbrito** [comment]
@MichaelSimons 

There is any chance to Visual Studio identify which package is referenced during Add Docker Support from Solution Explorer? And auto add apt-get some required packages?

![](https://user-images.githubusercontent.com/7241156/82770589-7aca5580-9e0f-11ea-8f92-53637409b947.png)

What do you think? So we can mitigate this kind of dependencies that isn't used on daily basis.

**Comment by MichaelSimons** [comment]
@brunohbrito - I like the way you are thinking but I see a couple downfalls with the suggestion of making `Add Docker Support` handle adding the dependencies.

1. It doesn't work for users who don't rely on the `Add Docker Support` functionality.  Users are free to use other IDEs such as VSCode.  Additionally there are VS users who have Dockerfiles managed outside of the `Add Docker Support` functionality.
2. This implies the package references exist at the time `Add Docker Support` is used.  What happens if the dependencies is added after the fact?

One path I lean towards is that when dependencies are missing, that the runtime self identifies and provides clear guidance for resolving.

**Comment by brunohbrito** [comment]
@MichaelSimons 

I thought something like this in .csproj: 
```xml
<PackageReference Include="System.DirectoryServices.Protocols" Version="5.0.0-preview.6.20272.2">
    <Dependency So="Linux" Package="libldap-2.4.so.2"/>
</PackageReference>
```
Then `Add Docker Support` or any other extension, or even vscode plugins could use this information.
I'm not sure if it overkill, but it works.

**Comment by MichaelSimons** [comment]
Copied comment from @richlander at https://github.com/dotnet/dotnet-docker/pull/2004#issuecomment-647849719

We have decided not to include this package in .NET container images, for any distro, and leaving it opt-in. This is due to the size impact. We consider the Directory Services API not to required by most containerized apps. We'd like feedback from folks that have other viewpoints.

**Comment by richlander** [comment]
If we were to really invest in this, we'd get the NuGet package itself to carry the Linux package reference. The Linux package reference can be updated at any time. Carrying it in the project file isn't great. It also makes the project limited to one distro. Package names and versions are frequently not the same across distros (Debian vs Alpine) and same with versions (Debian 9 vs 10).

This is an overly constrained problem. If more people ask for help on this, we'll consider doing something better. However, it's hard.

**Comment by mthalman** [comment]
cc @joperezr - Just an FYI that we've decided to not include the libldap package in our Docker images.

**Comment by mthalman** [comment]
Closing this per the decision to not include the libldap package in the Docker images. Feel free to keep the discussion going.

**Comment by istretyakov** [comment]
I'm sorry, i didn't catch what is solution of this problem.
For example, i have .NET 5.0 in Docker. And how can i use System.DirectoryServices.Protocols for connecting to Active Directory? What and how need i install?
I understood that some libs there aren't in .NET Docker images, but how to get round the problem?

**Comment by mthalman** [comment]
@istretyakov - You would need to install the appropriate LDAP library in your Dockerfile.  Examples provided below.

Debian/Ubuntu:

```Dockerfile
RUN apt-get update \
    && apt-get install -y --allow-unauthenticated \
        libldap \
    && rm -rf /var/lib/apt/lists/*
```

Alpine:

```Dockerfile
RUN apk add --no-cache \
        libldap
```

**Comment by istretyakov** [comment]
@mthalman maybe i need to create other issue, it's a question for me. I try to send LDAP request from Docker container.
In Windows-case i get response that server is unavailable. It's right. This response shows that request was sent. In other environment (work) i get users. With Docker and without Docker, on Windows.
But in Linux-case (Docker) each time i have this exception: The LDAP server returned an unknown error. I can write not existed server and i will get this exception. It means that doesn't work. And i added installing lib in Dockerfile, yes.
One code, different reactions.
Maybe i lost something extra libs, except for libldap-2.4-2?

Windows:
![Windows2](https://user-images.githubusercontent.com/25767039/115268126-9a165380-a142-11eb-85de-1b563c5b7648.jpg)

Linux:
![Linux2](https://user-images.githubusercontent.com/25767039/115268128-9b478080-a142-11eb-96d2-e2706fc30c58.jpg)

**Comment by mthalman** [comment]
@istretyakov - It seems you've gotten past the missing dependencies, otherwise the errors would be about the library not being found.  I would suggest filing a [discussion post](https://github.com/dotnet/runtime/discussions) on your issue.  Also, the `LdapException` should have an `ErrorCode` property that should provide the error code returned by the native LDAP library.

**Comment by adithyasai** [comment]
i am getting the following error

**Comment by istretyakov** [comment]
@adithyasai i'm sorry, i don't remember, but I think i solved to use this library:
https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard
I wanted to use library from System's space, but there isn't solution of this problem.

**Comment by brunohbrito** [comment]
> @adithyasai i'm sorry, i don't remember, but I think i solved to use this library: https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard I wanted to use library from System's space, but there isn't solution of this problem.

Actually this is the best way to deal with LDAP. This component is extremely fast to connect and there are lot of options. It's a native implementation, while System's space use the Dll Import.

**Comment by mthalman** [comment]
@adithyasai - Your Dockerfile is installing the package in a Dockerfile stage that's not being used when running your app. It's being installed in the `build` stage which is only used to build your project. That stage is not used when actually running the app.

Here's the suggested update:


```Dockerfile
#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libldap-2.4-2 \
    && rm -rf /var/lib/apt/lists/*

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Ldaptest1/Ldaptest1.csproj", "Ldaptest1/"]
RUN dotnet restore "Ldaptest1/Ldaptest1.csproj"
COPY . .
WORKDIR "/src/Ldaptest1"
RUN dotnet build "Ldaptest1.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Ldaptest1.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Ldaptest1.dll"]
```

**Comment by durranitech** [comment]
The alpine docker image for dotnet 7 preview 1 runs on alpine 3.15 and that has libldap 2.6 so hitting this problem again. I have to install libldap 2.4 to get it to work. Any chance libldap 2.6 will be supported in future dotnet preview?

**Comment by mthalman** [comment]
> The alpine docker image for dotnet 7 preview 1 runs on alpine 3.15 and that has libldap 2.6 so hitting this problem again. I have to install libldap 2.4 to get it to work. Any chance libldap 2.6 will be supported in future dotnet preview?

@joperezr - Are you aware of any compat issues with libldap 2.6?

**Comment by joperezr** [comment]
> @joperezr - Are you aware of any compat issues with libldap 2.6?

I haven't looked into 2.5 or 2.6 yet. We decided to PInvoke directly into 2.4 because at the time we added support for it, 2.4 had been released for 10+ years and there wasn't any indication that a new one would ship. Looks like 2.5 and 2.6 were released in late 2021 and introduced primarily load balancing support as well as transaction support. I don't think there should be anything preventing us from using 2.5 or 2.6 as well if present, so to answer @durranitech question, I believe that it would be feasible to think that a future version of dotnet will support them. Could you please log an issue on dotnet/runtime about this so we can investigate, assign and prioritize this?

**Comment by mthalman** [comment]
> I believe that it would be feasible to think that a future version of dotnet will support them

@joperezr - We need to ensure this works across all supported .NET versions (3.1, 5.0, 6.0). This is related to https://github.com/dotnet/core/issues/6985. In Alpine 3.15, libldap 2.6 is all that's available so we must support it.

**Comment by durranitech** [comment]
@joperezr should I still raise an issue for this or will this be looked at as part of the issue @mthalman referenced?

**Comment by mthalman** [comment]
> @joperezr should I still raise an issue for this or will this be looked at as part of the issue @mthalman referenced?

@durranitech - Yes, please log an issue at https://github.com/dotnet/runtime/issues if it's not working on Alpine 3.15.

**Comment by ChrisHolcomb** [comment]
> @adithyasai - Your Dockerfile is installing the package in a Dockerfile stage that's not being used when running your app. It's being installed in the `build` stage which is only used to build your project. That stage is not used when actually running the app.
> 
> Here's the suggested update:
> 
> ```dockerfile
> #See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.
> 
> FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
> WORKDIR /app
> EXPOSE 80
> EXPOSE 443
> 
> RUN apt-get update \
>     && apt-get install -y --no-install-recommends \
>         libldap-2.4-2 \
>     && rm -rf /var/lib/apt/lists/*
> 
> FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
> WORKDIR /src
> COPY ["Ldaptest1/Ldaptest1.csproj", "Ldaptest1/"]
> RUN dotnet restore "Ldaptest1/Ldaptest1.csproj"
> COPY . .
> WORKDIR "/src/Ldaptest1"
> RUN dotnet build "Ldaptest1.csproj" -c Release -o /app/build
> 
> FROM build AS publish
> RUN dotnet publish "Ldaptest1.csproj" -c Release -o /app/publish
> 
> FROM base AS final
> WORKDIR /app
> COPY --from=publish /app/publish .
> ENTRYPOINT ["dotnet", "Ldaptest1.dll"]
> ```

Did this work for anyone. I am having the same issue and tried the above but I'm still getting the same error

**Comment by richlander** [comment]
I was just reading this again. After thinking about it (and also recently talking to the Docker Tools for VS folks about something else), I do think that a VS solution is an OK direction. I get the point that it doesn't work for everyone/all places, but providing a value-add in VS for this would be good. The same would be said about ICU and Alpine.

**Comment by ChrisHolcomb** [comment]
So I finally did get this to work with the following docker file
`FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

RUN apt-get update \
    && apt-get install -y --no-install-recommends libldap-2.4-2 \
    && apt-get install -y --no-install-recommends libldap-common \
    && rm -rf /var/lib/apt/lists/* 
COPY ["Services/Identity/Identity.API/Certificate/ca_belcorpdc1.crt", "/usr/local/share/ca-certificates/"]
RUN chmod 644 /usr/local/share/ca-certificates/ca_belcorpdc1.crt && update-ca-certificates
COPY ["Services/Identity/Identity.API/Certificate/ldap.conf", "/etc/ldap/"] 

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Services/Identity/Identity.API/Identity.API.csproj", "Services/Identity/Identity.API/"]
RUN dotnet restore "Services/Identity/Identity.API/Identity.API.csproj"
COPY . .
WORKDIR "/src/Services/Identity/Identity.API/"
RUN dotnet build "Identity.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Identity.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Identity.API.dll"]
`
I was still having issues with my connection not working with the cert so I add the libldap-common package and copied over a ldap.conf file that set the "TLS_REQCERT  never", after that I was able to query the AD and authenticate users.

**Comment by anschauanderson** [comment]
I don't understand whay you use this

COPY ["Services/Identity/Identity.API/Certificate/ca_belcorpdc1.crt", "/usr/local/share/ca-certificates/"]
RUN chmod 644 /usr/local/share/ca-certificates/ca_belcorpdc1.crt && update-ca-certificates
COPY ["Services/Identity/Identity.API/Certificate/ldap.conf", "/etc/ldap/"] 

Where you get ca_belcorpdc1.crt?

**Comment by ChrisHolcomb** [comment]
Our system admin gave me the certificate so I copied to the project and this puts the certificate into the container and tells it to update it's certificates list.

**Comment by anschauanderson** [comment]
I have this error, Can you tell me what it could be?

System.DllNotFoundException: Unable to load shared library 'ldap.so.2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libldap.so.2: cannot open shared object file: No such file or directory
   at LdapForNet.Native.NativeMethodsLinux.ldap_initialize(IntPtr& ld, String uri)
   at LdapForNet.Native.LdapNativeLinux.Init(IntPtr& ld, String url)
   at LdapForNet.LdapConnection.Connect(String url, LdapVersion version)
   at LdapForNet.LdapConnectExtensions.Connect(ILdapConnection connection, Uri uri, LdapVersion version)
   at LdapForNet.LdapConnectExtensions.Connect(ILdapConnection connection, String hostname, Int32 port, LdapSchema ldapSchema, LdapVersion version)
   at Inlog.Fiscol.Domain.CommandHandlers.Account.LogarUsuarioCommandHandler.AuthenticateADUser(String userName, String password) in /src/Inlog.Fiscol.Domain/CommandHandlers/Account/LogarU

**Comment by ChrisHolcomb** [comment]
It looks like your container does not have the ldap library, That is what the RUN apt-get commands are for, they install it on the linux container.

Add
RUN apt-get update \
    && apt-get install -y --no-install-recommends libldap-2.4-2 \
    && apt-get install -y --no-install-recommends libldap-common \
    && rm -rf /var/lib/apt/lists/* 
to install the libraries. This needs to be installed on the base image which is used in the final build step.

**Comment by anschauanderson** [comment]
It's not working for me.

**Comment by sameerbaveja** [comment]
@ChrisHolcomb Can you please show your ldap.conf file. Below is my docker & its not working for me. 

#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM misnexusprd.corp.amdocs.com/microsoft-proxy/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM misnexusprd.corp.amdocs.com/microsoft-proxy/dotnet/sdk:5.0 AS build
WORKDIR /src


RUN apt-get update \
    && apt-get install -y --no-install-recommends libldap-2.4-2 \
    && apt-get install -y --no-install-recommends libldap-common \
    && rm -rf /var/lib/apt/lists/* 

COPY ./ResetPassword.WebAPI/ldap.conf /etc/ldap/

COPY ./ResetPassword.WebAPI/Amdocs_Root_Certification_Authority.crt /etc/ssl/certs/
COPY ./ResetPassword.WebAPI/AmdocsClass3SecureServerCA.crt /etc/ssl/certs/
COPY ./ResetPassword.WebAPI/amdocs.pem /etc/ssl/certs/
COPY NuGet.Config /root/.nuget/NuGet/NuGet.Config 

RUN update-ca-certificates
COPY ["./ResetPassword.WebAPI/ResetPassword.WebAPI.csproj", "ResetPassword.WebAPI/"]
COPY ["./ResetPassword.Core/ResetPassword.Core.csproj", "ResetPassword.Core/"]
RUN dotnet restore "ResetPassword.WebAPI/ResetPassword.WebAPI.csproj"
COPY . .
WORKDIR "/src/ResetPassword.WebAPI"
RUN dotnet build "ResetPassword.WebAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ResetPassword.WebAPI.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ResetPassword.WebAPI.dll"]

**Comment by sameerbaveja** [comment]
@ChrisHolcomb  Its still not working for me :(

I am getting below error : 

**Unexpected error: System.DllNotFoundException: Unable to load shared library 'libldap-2.4.so.2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibldap-2.4.so.2: cannot open shared object file: No such file or directory\n   at Interop.Ldap.ldap_get_option_int(IntPtr ldapHandle, LdapOption option, Int32& outValue)\n   at Interop.Ldap..cctor()**

Below is my docker : 

#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.


FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
expose 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src

RUN apt-get update \
    && apt-get install -y --no-install-recommends libldap-2.4-2 \
    && apt-get install -y --no-install-recommends libldap-common \
    && rm -rf /var/lib/apt/lists/* 

COPY ./ResetPassword.WebAPI/ldap.conf /etc/ldap/

COPY ./ResetPassword.WebAPI/Amdocs_Root_Certification_Authority.crt /etc/ssl/certs/
COPY ./ResetPassword.WebAPI/AmdocsClass3SecureServerCA.crt /etc/ssl/certs/
COPY ./ResetPassword.WebAPI/amdocs.pem /etc/ssl/certs/
COPY NuGet.Config /root/.nuget/NuGet/NuGet.Config 
RUN update-ca-certificates

COPY ["ResetPassword.WebAPI/ResetPassword.WebAPI.csproj", "ResetPassword.WebAPI/"]
COPY ["ResetPassword.Core/ResetPassword.Core.csproj", "ResetPassword.Core/"]
RUN dotnet restore "ResetPassword.WebAPI/ResetPassword.WebAPI.csproj"
COPY . .
WORKDIR "/src/ResetPassword.WebAPI"
RUN dotnet build "ResetPassword.WebAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ResetPassword.WebAPI.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ResetPassword.WebAPI.dll"]

**Comment by anschauanderson** [comment]
I changed lib, 

Now i am using [Novell.Directory.Ldap.NETStandard](https://www.nuget.org/packages/Novell.Directory.Ldap.NETStandard/) and it's working for me to connect at Active Derectory From Docker / Linux;

**Comment by anschauanderson** [comment]
```
private bool AuthenticateADUser(string userName, string password)
        {
            bool ret = false;

            try
            {
                using (var cn = new Novell.Directory.Ldap.LdapConnection())
                {
                    // Ldap URL, in my case 10.150.16.12
                    cn.Connect(_"10.150.16.12", 389);
                    // This is necessary username@domain ex. anderson@inlog
                    cn.Bind(userName + "@inlog", password);
                    ret = true;
                }

            }
            catch (Exception x)
            {
                Console.WriteLine(x.ToString());
                ret = false;
            }

            return ret;
        }
```

**Comment by ChrisHolcomb** [comment]
> @ChrisHolcomb Its still not working for me :(
> 
> I am getting below error :
> 
> **Unexpected error: System.DllNotFoundException: Unable to load shared library 'libldap-2.4.so.2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibldap-2.4.so.2: cannot open shared object file: No such file or directory\n at Interop.Ldap.ldap_get_option_int(IntPtr ldapHandle, LdapOption option, Int32& outValue)\n at Interop.Ldap..cctor()**
> 
> Below is my docker :
> 
> #See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.
> 
> FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base WORKDIR /app EXPOSE 80 expose 443
> 
> FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build WORKDIR /src
> 
> RUN apt-get update && apt-get install -y --no-install-recommends libldap-2.4-2 && apt-get install -y --no-install-recommends libldap-common && rm -rf /var/lib/apt/lists/*
> 
> COPY ./ResetPassword.WebAPI/ldap.conf /etc/ldap/
> 
> COPY ./ResetPassword.WebAPI/Amdocs_Root_Certification_Authority.crt /etc/ssl/certs/ COPY ./ResetPassword.WebAPI/AmdocsClass3SecureServerCA.crt /etc/ssl/certs/ COPY ./ResetPassword.WebAPI/amdocs.pem /etc/ssl/certs/ COPY NuGet.Config /root/.nuget/NuGet/NuGet.Config RUN update-ca-certificates
> 
> COPY ["ResetPassword.WebAPI/ResetPassword.WebAPI.csproj", "ResetPassword.WebAPI/"] COPY ["ResetPassword.Core/ResetPassword.Core.csproj", "ResetPassword.Core/"] RUN dotnet restore "ResetPassword.WebAPI/ResetPassword.WebAPI.csproj" COPY . . WORKDIR "/src/ResetPassword.WebAPI" RUN dotnet build "ResetPassword.WebAPI.csproj" -c Release -o /app/build
> 
> FROM build AS publish RUN dotnet publish "ResetPassword.WebAPI.csproj" -c Release -o /app/publish
> 
> FROM base AS final WORKDIR /app COPY --from=publish /app/publish . ENTRYPOINT ["dotnet", "ResetPassword.WebAPI.dll"]

That won't work. You are installer the library in the Build container not the Base container.

**Comment by richlander** [comment]
This issue is still getting significant activity. I propose we update the error message, like the following:

```bash
Unable to load shared library 'libldap-2.4.so.2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibldap-2.4.so.2: cannot open shared object file: No such file or directory

See https://aka.ms/dotnet/ldap-dependency to learn more.
```

From a container standpoint, I think think we made the best choice, to not install the ldap component. However, we need to do more to make this dependency problem self-diagnosable.

Also, this document doesn't make any mention of a dangling dependency: https://docs.microsoft.com/dotnet/api/system.directoryservices.protocols.ldapconnection.

Related, this dependency likely isn't constant across all distros. We should capture that somewhere, possibly at https://github.com/dotnet/core/blob/main/release-notes/6.0/linux-packages.md.
