### ISSUE TITLE
aspnet Alpine image does not connect with SQL database

### ISSUE THREAD

**Issue by navarroaxel** [dotnet/dotnet-docker#2346]
### Describe the Bug

I can't connect to MSSQL using `mcr.microsoft.com/dotnet/core/aspne:3.1-alpine`

```
"System.NotSupportedException: Globalization Invariant Mode is not supported.
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()\n   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)\n   at Staks.Data.Repositories.UserRepository.GetByAuthIdAsync(Guid authId) in /src/Staks.Data/Repositories/UserRepository.cs:line 27\n   at Staks.Api.Controllers.AccountController.GetAccountAsync() in /src/Staks.Api/Controllers/AccountController.cs:line 46\n   at lambda_method(Closure , Object )\n   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"
}
{"level":"Error","id":"0HM3QN9SMJF07:00000003","user":"4
```

### Steps to Reproduce

Just try to deploy a web app using EF.

### Other Information

The Alpine image is fixed with:
```Dockerfile
RUN apk add icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
```

### Output of `docker version`

```
Docker version 19.03.13-ce, build 4484c46d9d
```

### Output of `docker info`
 ```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 19.03.13-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: c623d1b36f09f8ef6536a057bd658b3aa8632828.m
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.9.1-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.13GiB
 Name: IRONNB
 ID: 6DIM:GZFL:LSXA:5IEL:EHDH:33FN:C7WU:XKAR:4RHZ:U7IX:GTWO:KG4S
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by Gabriiell** [comment]
If `icu` pkg is well configured in `mcr.microsoft.com/dotnet/core/runtime-deps:3.1-alpine` as runtime dependency, it would work without any extra settings in aspnet Dockerfile

**Comment by MichaelSimons** [comment]
@navarroaxel, Can you share your Dockerfile?  Are you saying that you have added `icu-libs` and disabled `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` in your Dockerfile?

Excluding `icu-libs` from the Alpine images is intentional as it is not required for a large number of scenarios and adds significant size.  See https://github.com/dotnet/announcements/issues/20 for details.

**Comment by navarroaxel** [comment]
But the `runtime-deps` image has only 10MB :thinking: 

```Dockerfile
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build
WORKDIR /src

COPY ["Api/Api.csproj", "Api/"]

RUN dotnet restore "Api/Api.csproj"

COPY . .
WORKDIR "/src/Api"
RUN dotnet build "Api.csproj" --configuration Release --output /app/build --no-restore

RUN dotnet publish "Api.csproj" --configuration Release --output /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine AS final
# Fix based on https://github.com/dotnet/SqlClient/issues/220
RUN apk add icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 80
EXPOSE 443
ENTRYPOINT ["dotnet", "Api.dll"]
```

**Comment by MichaelSimons** [comment]
The goals of the Alpine images is to provide an offering which is both small in size and secure.  Adding `icu-libs` does not align with these goals.  It makes the image 43 MB on disk as well as increases the attack surface area.  The .NET base images are intended to be a foundation for you to use.  It is intended that users will need to add the requirements specific to their use cases.

**Comment by MichaelSimons** [comment]
I clarified my earlier comment inline - adding `icu-libs` to the `runtime-deps` image would make it 43MB versus the current 9.86MB.  The `runtime-deps` is where the globalization invariant mode is enabled.  Can you clarify what you are asking/proposing?

**Comment by navarroaxel** [comment]
I will change my question. Why the CLI taskcore app works properly in `runtime-deps` but my aspnet website can't connect to EF?

The solution that I found was this:
```Dockerfile
RUN apk add icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
```

Is there a simpler and lighter solution possible for the aspnet docker image?

**Comment by MichaelSimons** [comment]
When you say simpler and lighter, are you concerned about the size/surface area or are you looking for a ready made solution?

The underlying issue is that the SqlClient does not support the globalization invariant mode.  See  https://github.com/dotnet/SqlClient/issues/220 for the discussion.

**Comment by mdsacra** [comment]
This problem still persists in .NET 5.0

**Comment by mthalman** [comment]
> This problem still persists in .NET 5.0

That's because invariant mode continues to be enabled in Alpine for 5.0. This will be true for 6.0 as well.  There are no plans to change this based on our [philosophy for Alpine](https://github.com/dotnet/dotnet-docker/issues/2346#issuecomment-718158651).

To workaround this, follow the [solution provided above](https://github.com/dotnet/dotnet-docker/issues/2346#issuecomment-718181143).

**Comment by mdsacra** [comment]
> > This problem still persists in .NET 5.0
> 
> That's because invariant mode continues to be enabled in Alpine for 5.0. This will be true for 6.0 as well. There are no plans to change this based on our [philosophy for Alpine](https://github.com/dotnet/dotnet-docker/issues/2346#issuecomment-718158651).
> 
> To workaround this, follow the [solution provided above](https://github.com/dotnet/dotnet-docker/issues/2346#issuecomment-718181143).

Thanks for your reply. It's make sense. Sorry, I didn't read the comment that you mentioned.
