### ISSUE TITLE
TLS Error While Connecting to MySQL 5.6

### ISSUE THREAD

**Issue by random7192** [dotnet/dotnet-docker#2503]
I upgraded to dot net core 5.0 .

I am connecting to Mysql on RDS.  From visual studio everything works fine.

But from docker image  i get a connection error SSL Handshake failed with OpenSSL error

` Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:1421C105:SSL routines:set_client_ciphersuite:wrong cipher returned
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at MySql.Data.Common.Ssl.StartSSL(Stream& baseStream, Encoding encoding, String connectionString)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()`

My Docker image is using the below base image 

`FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine AS base

WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build`

**Comment by adamhathcock** [comment]
I've had a similar issue connecting to Aurora MySQL 5.7:
```
MySqlConnector.MySqlException (0x80004005): SSL Authentication Error

---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.

---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.

---> Interop+Crypto+OpenSslCryptographicException: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure

--- End of inner exception stack trace ---

at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)

at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)

--- End of inner exception stack trace ---

at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)

at System.Net.Security.SslStream.ProcessAuthentication(Boolean isAsync, Boolean isApm, CancellationToken cancellationToken)

at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)

at MySqlConnector.Core.ServerSession.InitSslAsync(ProtocolCapabilities serverCapabilities, ConnectionSettings cs, SslProtocols sslProtocols, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 1356
```

Switching back to debian for now

**Comment by adamhathcock** [comment]
I know my problem is probably ignorance of configuring Alpine but I don't know where to look.  All I did was update from 3.10 to 5.02 and got that.

My Aurora MySQL supports TLS 1  to 1.2 which hasn't changed
![image](https://user-images.githubusercontent.com/527620/105201763-23fd5300-5b39-11eb-8079-43aceeb5f9b8.png)

**Comment by MichaelSimons** [comment]
Can you clarify what docker image (specifically the tag) you were previously using?  Was it the latest 3.1 Alpine image or if it was an older 3.1 version.  Providing the image digest you were using would be helpful.

**Comment by adamhathcock** [comment]
We went from `mcr.microsoft.com/dotnet/core/aspnet:3.1.10-alpine3.12` to `mcr.microsoft.com/dotnet/core/aspnet:5.0.2-alpine3.12` and only noticed any issue when deploying.

Locally, on various OSes, there had been no issue.  Of course, we didn't test TLS til doing a test deploy.

**Comment by salmonz** [comment]
Experienced the exact same issue. Reverted to using Debian for now. I haven’t done a full investigation, but I suspect it’s due to the recent change made in .NET 5 where some default ciphers are used and the ciphers AWS Aurora use are not the same. As well, since there’s so many moving parts, what is different between .NET 5.0 and .NET 3.1 and the alpine versions used in the respective docker images.

**Comment by MichaelSimons** [comment]
As @salmonz referenced, this appears related to https://docs.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/default-cipher-suites-for-tls-on-linux.

The runtime issue https://github.com/dotnet/runtime/issues/47117 has some remediation links.

**Comment by MichaelSimons** [comment]
[Triage] Closing as this a designed behavior change w/5.0.

**Comment by ajaysuwalka** [comment]
Changing FROM `mcr.microsoft.com/dotnet/aspnet:5.0.10-focal` to `FROM mcr.microsoft.com/dotnet/aspnet:5.0` Helped me

Basically focal images have this issue hence use non focal images

**Comment by Juniogont** [comment]
> Changing FROM `mcr.microsoft.com/dotnet/aspnet:5.0.10-focal` to `FROM mcr.microsoft.com/dotnet/aspnet:5.0` Helped me
> 
> Basically focal images have this issue hence use non focal images
ajaysuwalka, This solution  works for me. Tks for the tip.
