### ISSUE TITLE
The dotnetsdk container dev-certs appear broken, (5.0-windowsservercore-ltsc2019)

### ISSUE THREAD

**Issue by aaronla-ms** [dotnet/dotnet-docker#2860]
The dev-certs in the "" container image appear to be "damaged" in the sense that 

1. unit test that rely on that dev cert fail
2. `dotnet dev-certs https --clean` doesn't actually remove the damaged cert

### Steps to Reproduce

Both repros were tests with container `mcr.microsoft.com/dotnet/sdk:5.0-windowsservercore-ltsc2019` with image id `f0899d235b9c`

Repro steps (1) unable to remove damaged cert:

```
aaronla@aaronla-xyz:dev1$ docker run --mount type=bind,source=d:\repos,target=c:\repos --name inst-dev-2 -it mcr.microsoft.com/dotnet/sdk:5.0-windowsservercore-ltsc2019
Microsoft Windows [Version 10.0.17763.1935]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\>powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\> dir Cert:\CurrentUser\My\ | fl


Subject      : CN=localhost
Issuer       : CN=localhost
Thumbprint   : 8249B46C6BC1C7CE30BF7A51DC0DB8C1E6C5BDB2
FriendlyName : ASP.NET Core HTTPS development certificate
NotBefore    : 5/25/2021 8:38:32 AM
NotAfter     : 5/25/2022 8:38:32 AM
Extensions   : {System.Security.Cryptography.Oid, System.Security.Cryptography.Oid, System.Security.Cryptography.Oid,
               System.Security.Cryptography.Oid...}



PS C:\> dotnet dev-certs https --clean
Cleaning HTTPS development certificates from the machine. A prompt might get displayed to confirm the removal of some of the
 certificates.
HTTPS development certificates successfully removed from the machine.
PS C:\> dir Cert:\CurrentUser\My\ | fl


Subject      : CN=localhost
Issuer       : CN=localhost
Thumbprint   : 8249B46C6BC1C7CE30BF7A51DC0DB8C1E6C5BDB2
FriendlyName : ASP.NET Core HTTPS development certificate
NotBefore    : 5/25/2021 8:38:32 AM
NotAfter     : 5/25/2022 8:38:32 AM
Extensions   : {System.Security.Cryptography.Oid, System.Security.Cryptography.Oid, System.Security.Cryptography.Oid,
               System.Security.Cryptography.Oid...}
```

[expected]
Cert removed by the --clean step.

[actual]
As seen above, cert still present.

Repro steps (2) tests failing due to bad cert:

(reference repo, MSFT FTE only: https://msazure.visualstudio.com/One/_git/PowerApps-CoreServicesGateway?path=%2F&version=GBdev%2Faaronla%2Fnew-image&_a=contents )
```
C:\repos\PowerApps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests>dotnet test --no-build --filter IntegrationTe
sts.HealthApi_ShouldReturn200
Test run for C:\repos\PowerApps-CoreServicesGateway\out\testbin\Debug-x64\Microsoft.PowerPlatform.CoreServices.PPApiGateway.
Tests\Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.dll (.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.10.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:01.40]     Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.IntegrationTests.HealthApi_ShouldReturn2
00 [FAIL]
  Failed Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.IntegrationTests.HealthApi_ShouldReturn200 [156 ms]
  Error Message:
   System.InvalidOperationException : Unable to configure HTTPS endpoint. No server certificate was specified, and the defau
lt developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dot
net dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
  Stack Trace:
     at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOp
tions)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context
)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelSe
rverOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, Cancellati
onToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.Start()
   at Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.IntegrationTests.TestSetup.RunTestEchoServiceServer() in C:\re
pos\PowerApps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests\IntegrationTests.cs:line 182
   at Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.IntegrationTests.TestSetup.Run(String host, Func`2 func) in C:
\repos\PowerApps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests\IntegrationTests.cs:line 165
   at Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.IntegrationTests.HealthApi_ShouldReturn200() in C:\repos\Power
Apps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests\IntegrationTests.cs:line 40
--- End of stack trace from previous location where exception was thrown ---

Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: < 1 ms - Microsoft.PowerPlatform.CoreServic
es.PPApiGateway.Tests.dll (netcoreapp3.1)

C:\repos\PowerApps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests>dotnet dev-certs https
The HTTPS developer certificate was generated successfully.

C:\repos\PowerApps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests>dotnet test --no-build --filter IntegrationTe
sts.HealthApi_ShouldReturn200
Test run for C:\repos\PowerApps-CoreServicesGateway\out\testbin\Debug-x64\Microsoft.PowerPlatform.CoreServices.PPApiGateway.
Tests\Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.dll (.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.10.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:01.40]     Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.IntegrationTests.HealthApi_ShouldReturn2
00 [FAIL]
  Failed Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.IntegrationTests.HealthApi_ShouldReturn200 [160 ms]
  Error Message:
   System.InvalidOperationException : Unable to configure HTTPS endpoint. No server certificate was specified, and the defau
lt developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dot
net dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
  Stack Trace:
     at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOp
tions)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context
)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelSe
rverOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, Cancellati
onToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.Start()
   at Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.IntegrationTests.TestSetup.RunTestEchoServiceServer() in C:\re
pos\PowerApps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests\IntegrationTests.cs:line 182
   at Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.IntegrationTests.TestSetup.Run(String host, Func`2 func) in C:
\repos\PowerApps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests\IntegrationTests.cs:line 165
   at Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.IntegrationTests.HealthApi_ShouldReturn200() in C:\repos\Power
Apps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests\IntegrationTests.cs:line 40
--- End of stack trace from previous location where exception was thrown ---

Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: < 1 ms - Microsoft.PowerPlatform.CoreServic
es.PPApiGateway.Tests.dll (netcoreapp3.1)

C:\repos\PowerApps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests>powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\repos\PowerApps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests> ls Cert:\CurrentUser\My\


   PSParentPath: Microsoft.PowerShell.Security\Certificate::CurrentUser\My

Thumbprint                                Subject
----------                                -------
CFCFF10B7247EAF1993909FD73E893939AD4E8F5  CN=localhost
8249B46C6BC1C7CE30BF7A51DC0DB8C1E6C5BDB2  CN=localhost


PS C:\repos\PowerApps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests> rm Cert:\CurrentUser\My\8249B46C6BC1C7CE3
0BF7A51DC0DB8C1E6C5BDB2
PS C:\repos\PowerApps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests> exit

C:\repos\PowerApps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests>dotnet test --no-build --filter IntegrationTe
sts.HealthApi_ShouldReturn200
Test run for C:\repos\PowerApps-CoreServicesGateway\out\testbin\Debug-x64\Microsoft.PowerPlatform.CoreServices.PPApiGateway.
Tests\Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.dll (.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.10.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: < 1 ms - Microsoft.PowerPlatform.CoreServic
es.PPApiGateway.Tests.dll (netcoreapp3.1)
```

[expected]
test passes first time, using the preconfigured dev-certs

[actual]
test fails until the preconfigured dev-cert is removed, and a new (functioning) cert added.

NOTE: the test in question is on netcoreapp3.1, built using net50 sdk.

### Output of `docker version`

```
$ docker --version
Docker version 20.10.6, build 370c289
```

### Output of `docker info`

```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 21
 Server Version: 20.10.6
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 19043 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Windows 10 Pro Version 2009 (OS Build 19043.985)
 OSType: windows
 Architecture: x86_64
 CPUs: 6
 Total Memory: 31.92GiB
 Name: aaronla-xyz
 ID: UGKB:MTXE:D2VT:7P5E:5SDX:5S26:ET6R:NC65:JSXP:XHFS:3BGB:QTO2
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by MichaelSimons** [comment]
[Triage] This certificate was removed in the 6.0 images with https://github.com/dotnet/dotnet-docker/pull/2710.  @mthalman, can you please take a look at this issue?

**Comment by mthalman** [comment]
Ok, so my preliminary findings show that the cert weirdness is somehow related to the image layers.  The cert only behaves this way if it's been stored in a layer.

First, I should mention how the cert ends up in the image.  It gets created as part of the first-run experience for the `dotnet` CLI.  For this Dockerfile, that happens when installing PowerShell Core:

https://github.com/dotnet/dotnet-docker/blob/f9819629e30bf3c0be7bf68e038fc4bb16dd1e20/src/sdk/5.0/windowsservercore-ltsc2019/amd64/Dockerfile#L39

So that's the layer in which the cert gets created in the official image.

Here's a slimmed down example that shows how the layer is interacting with this issue:

```Dockerfile
# escape=`

ARG REPO=mcr.microsoft.com/dotnet/aspnet
FROM $REPO:5.0-windowsservercore-ltsc2019

ENV `
    # Unset ASPNETCORE_URLS from aspnet base image
    ASPNETCORE_URLS= `
    DOTNET_SDK_VERSION=5.0.301 `
    # Enable correct mode for dotnet watch (only mode supported in a container)
    DOTNET_USE_POLLING_FILE_WATCHER=true `
    # Skip extraction of XML docs - generally not useful within an image/container - helps performance
    NUGET_XMLDOC_MODE=skip `
    # PowerShell telemetry for docker image usage
    POWERSHELL_DISTRIBUTION_CHANNEL=PSDocker-DotnetSDK-WindowsServerCore-ltsc2019

RUN powershell -Command "`
        $ErrorActionPreference = 'Stop'; `
        $ProgressPreference = 'SilentlyContinue'; `
        `
        # Retrieve .NET SDK
        Invoke-WebRequest -OutFile dotnet.zip https://dotnetcli.azureedge.net/dotnet/Sdk/$Env:DOTNET_SDK_VERSION/dotnet-sdk-$Env:DOTNET_SDK_VERSION-win-x64.zip; `
        $dotnet_sha512 = 'e16e06a9da022c2867aa3dfc0a3d0f278ca59a08991c066ebd3fb4fe8790639b74c9b352922e9b7a58cdce644b5ab0b15d995b8717426f3cd13053bc3d8c1dc5'; `
        if ((Get-FileHash dotnet.zip -Algorithm sha512).Hash -ne $dotnet_sha512) { `
            Write-Host 'CHECKSUM VERIFICATION FAILED!'; `
            exit 1; `
        }; `
        tar -C $Env:ProgramFiles\dotnet -oxzf dotnet.zip ./packs ./sdk ./templates ./LICENSE.txt ./ThirdPartyNotices.txt ./shared/Microsoft.WindowsDesktop.App; `
        Remove-Item -Force dotnet.zip;"

RUN dotnet help
```

Building and running this produces a container that cannot have the cert cleaned.  Here I'm running the resulting container interactively.

```console
Microsoft Windows [Version 10.0.17763.1999]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\>powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\> dir Cert:\CurrentUser\My\ | fl


Subject      : CN=localhost
Issuer       : CN=localhost
Thumbprint   : 829CFD2B03FAFB8D86E7CD290F7002B186F55859
FriendlyName : ASP.NET Core HTTPS development certificate
NotBefore    : 6/10/2021 3:46:31 PM
NotAfter     : 6/10/2022 3:46:31 PM
Extensions   : {System.Security.Cryptography.Oid, System.Security.Cryptography.Oid, System.Security.Cryptography.Oid, System.Security.Cryptography.Oid...}



PS C:\> dotnet dev-certs https --clean
Cleaning HTTPS development certificates from the machine. A prompt might get displayed to confirm the removal of some of the certificates.
HTTPS development certificates successfully removed from the machine.
PS C:\> dir Cert:\CurrentUser\My\ | fl


Subject      : CN=localhost
Issuer       : CN=localhost
Thumbprint   : 829CFD2B03FAFB8D86E7CD290F7002B186F55859
FriendlyName : ASP.NET Core HTTPS development certificate
NotBefore    : 6/10/2021 3:46:31 PM
NotAfter     : 6/10/2022 3:46:31 PM
Extensions   : {System.Security.Cryptography.Oid, System.Security.Cryptography.Oid, System.Security.Cryptography.Oid, System.Security.Cryptography.Oid...}
```

Ok, let's remove the last line from the Dockerfile, `RUN dotnet help`, and run that container interactively:

```console
Microsoft Windows [Version 10.0.17763.1999]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\>powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\> dir Cert:\CurrentUser\My\ | fl
PS C:\> dotnet help

Welcome to .NET 5.0!
---------------------
SDK Version: 5.0.301

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '
1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
Usage: dotnet [runtime-options] [path-to-application] [arguments]

Execute a .NET application.

runtime-options:
  --additionalprobingpath <path>   Path containing probing policy and assemblies to probe for.
  --additional-deps <path>         Path to additional deps.json file.
  --depsfile                       Path to <application>.deps.json file.
  --fx-version <version>           Version of the installed Shared Framework to use to run the application.
  --roll-forward <setting>         Roll forward to framework version  (LatestPatch, Minor, LatestMinor, Major, LatestMajor, Disable).
  --runtimeconfig                  Path to <application>.runtimeconfig.json file.

  The path to an application .dll file to execute.


Execute a .NET SDK command.

sdk-options:
  -d|--diagnostics  Enable diagnostic output.
  -h|--help         Show command line help.
  --info            Display .NET information.
  --list-runtimes   Display the installed runtimes.
  --list-sdks       Display the installed SDKs.
  --version         Display .NET SDK version in use.

SDK commands:
  add               Add a package or reference to a .NET project.
  build             Build a .NET project.
  build-server      Interact with servers started by a build.
  clean             Clean build outputs of a .NET project.
  help              Show command line help.
  list              List project references of a .NET project.
  msbuild           Run Microsoft Build Engine (MSBuild) commands.
  new               Create a new .NET project or file.
  nuget             Provides additional NuGet commands.
  pack              Create a NuGet package.
  publish           Publish a .NET project for deployment.
  remove            Remove a package or reference from a .NET project.
  restore           Restore dependencies specified in a .NET project.
  run               Build and run a .NET project output.
  sln               Modify Visual Studio solution files.
  store             Store the specified assemblies in the runtime package store.
  test              Run unit tests using the test runner specified in a .NET project.
  tool              Install or manage tools that extend the .NET experience.
  vstest            Run Microsoft Test Engine (VSTest) commands.

Additional commands from bundled tools:
  dev-certs         Create and manage development certificates.
  fsi               Start F# Interactive / execute F# scripts.
  sql-cache         SQL Server cache command-line tools.
  user-secrets      Manage development user secrets.
  watch             Start a file watcher that runs a command when files change.

Run 'dotnet [command] --help' for more information on a command.
PS C:\> dir Cert:\CurrentUser\My\ | fl


Subject      : CN=localhost
Issuer       : CN=localhost
Thumbprint   : A4B9C78D2FA3203110E363FE70E84FFF7B5DBD7F
FriendlyName : ASP.NET Core HTTPS development certificate
NotBefore    : 6/10/2021 4:11:35 PM
NotAfter     : 6/10/2022 4:11:35 PM
Extensions   : {System.Security.Cryptography.Oid, System.Security.Cryptography.Oid, System.Security.Cryptography.Oid, System.Security.Cryptography.Oid...}



PS C:\> dotnet dev-certs https --clean
Cleaning HTTPS development certificates from the machine. A prompt might get displayed to confirm the removal of some of the certificates.
HTTPS development certificates successfully removed from the machine.
PS C:\> dir Cert:\CurrentUser\My\ | fl
PS C:\>
```

By causing the cert to be added during the interactive session it can be successfully cleaned.  So it doesn't exhibit this strange behavior.  This isn't just an "interactive" thing. The same commands could be done within a single `RUN` instruction of a Dockerfile and you'd get the same behavior because it's all in one layer.

I'll keep digging on why this happens.

**Comment by mthalman** [comment]
@javiercn - Can you offer some input here?

I've attempted to repro this behavior (the inability to delete the cert) outside the context of the dev-certs tool by copying some of the tool's code into a console app that runs in a container with the cert already installed.  But the cert gets deleted fine.  I'm not exactly sure why my attempt isn't getting the same behavior.

I do see in the code that there is a bunching of logging going on.  Is there a simple way to output that logging information when invoking `dev-certs https --clean`?

**Comment by MichaelSimons** [comment]
Transferring to the aspnet repo to investigate the dev-certs behavior in Windows containers.
