### ISSUE TITLE
Use 3-part version tag in FROM instruction

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#2885]
For all Dockerfiles which have a .NET image tag referenced in a `FROM` instruction, the referenced tag should use the 3-part version number instead of the 2-part number.  This maintains coherency when attempting to build older Dockerfiles whose versions are not currently the latest anymore.

For example, the current version for .NET 5 is 5.0.7.  If I grab the [aspnet Dockerfile for 5.0.6](https://github.com/dotnet/dotnet-docker/blob/5d9e2099db7d73b97a9008ec948dcade7b34904b/src/aspnet/5.0/buster-slim/amd64/Dockerfile) and attempt to build it with nothing cached on my machine, it will pull the latest runtime version, 5.0.7, because it's referencing the tag with the 2-part version number tag, a floating tag which gets updated with each servicing release to point to the latest version:

https://github.com/dotnet/dotnet-docker/blob/5d9e2099db7d73b97a9008ec948dcade7b34904b/src/aspnet/5.0/buster-slim/amd64/Dockerfile#L17

This causes an image to be built that contains incompatible runtimes, 5.0.6 .NET runtime and 5.0.7 ASP.NET Core.

Instead, to always guarantee coherency, such Dockerfiles should reference the matching 3-part version for which the Dockerfile represents.  In this case, the 5.0.6 aspnet Dockerfile should reference the 5.0.6 runtime tag: `FROM $REPO:5.0.6-buster-slim-amd64`.

Inspired by https://github.com/dotnet/dotnet-docker/issues/2843

**Comment by mthalman** [comment]
This requires infrastructure work in Image Builder.  Adding another ARG to the Dockerfile currently requires the manifest file to explicitly provide a value for it in the buildArgs field.  We just can't define a default value for it in the Dockerfile and leave the manifest unchanged and expect things to work with the logic that Image Builder has today.

As an example, here's a snippet of the proposed Dockerfile change:

```Dockerfile
ARG REPO=mcr.microsoft.com/dotnet/runtime-deps
ARG DOTNET_VERSION=2.1.28
FROM $REPO:$DOTNET_VERSION-stretch-slim
```

This will result in an exception when loading the manifest:

```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: A value was not found for the ARG '$DOTNET_VERSION-stretch-slim' in `src/runtime/2.1/stretch-slim/amd64/Dockerfile`
   at Microsoft.DotNet.ImageBuilder.ViewModel.PlatformInfo.SubstituteBuildArgs(String instruction) in /image-builder/src/ViewModel/PlatformInfo.cs:line 286
   at Microsoft.DotNet.ImageBuilder.ViewModel.PlatformInfo.<>c__DisplayClass74_0.<InitializeFromImages>b__2(String from) in /image-builder/src/ViewModel/PlatformInfo.cs:line 120
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.ImageBuilder.ViewModel.PlatformInfo.InitializeFromImages() in /image-builder/src/ViewModel/PlatformInfo.cs:line 117
   at Microsoft.DotNet.ImageBuilder.ViewModel.PlatformInfo.Initialize(IEnumerable`1 internalRepos, String registry) in /image-builder/src/ViewModel/PlatformInfo.cs:line 77
   at Microsoft.DotNet.ImageBuilder.ViewModel.ManifestInfo.Create(String manifestPath, ManifestFilter manifestFilter, IManifestOptionsInfo options) in /image-builder/src/ViewModel/ManifestInfo.cs:line 92
   at Microsoft.DotNet.ImageBuilder.ViewModel.ManifestInfo.Load(IManifestOptionsInfo options) in /image-builder/src/ViewModel/ManifestInfo.cs:line 45
   at Microsoft.DotNet.ImageBuilder.Commands.ManifestCommand`2.LoadManifest() in /image-builder/src/Commands/ManifestCommand.cs:line 19
   at Microsoft.DotNet.ImageBuilder.Commands.ManifestCommand`2.Initialize(TOptions options) in /image-builder/src/Commands/ManifestCommand.cs:line 26
   at Microsoft.DotNet.ImageBuilder.Commands.Command`2.<GetCliCommand>b__9_0(TOptions options) in /image-builder/src/Commands/Command.TOptions.cs:line 45
```

The proper thing to do here is to update Image Builder to not require explicit setting of ARG values from the manifest.

**Comment by mthalman** [comment]
I've realized that this is more than just not requiring ARG values to be defined in the manifest.  Even if that was implemented, there would be further issues because Image Builder requires that the FROM image values be resolved in order to properly reason about the dependency.  Let's use this Dockerfile as an example:

```Dockerfile
ARG REPO=mcr.microsoft.com/dotnet/runtime-deps
ARG DOTNET_VERSION=2.1.28
FROM $REPO:$DOTNET_VERSION-stretch-slim
```

Image Builder would resolve the FROM value down to `mcr.microsoft.com/dotnet/runtime-deps:$DOTNET_VERSION-stretch-slim`. But that's not enough. It needs to know the resolved value of the `DOTNET_VERSION` argument for proper string matching amongst all sorts of Image Builder logic.

Being able to resolve the reference arg to the ARG value is not trivial regex work. It requires semantic knowledge of the Dockerfile structure to do it correctly. There does happen to be a library that does this kind of parsing: https://github.com/dotnet/docker-tools/pull/752.

**Comment by mthalman** [comment]
Because of these issues, I'm going to avoid the use of referencing an ARG in the FROM value and instead inject the version number directly from the Dockerfile template. This introduces a bit of duplication within the template but it's minimal.
