### ISSUE TITLE
AspnetImageTests.VerifyAppScenario test failing for 7.0 on distroless Mariner

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#3448]
The test is failing, unable to access the access point to verify the app container is running. This test succeeded in the PR build and also succeeds locally on my machine. It only fails on the internal build. My guess is that it fails as a result of running it in the `NetCore1ESPool-Internal` pool which was just introduced in https://github.com/dotnet/dotnet-docker/pull/3443. No idea on what kind of configuration the agent could have that would cause this to fail and have it be specific to the distroless Mariner scenario.

```
Error Message:
   System.TimeoutException : Timed out attempting to access the endpoint http://172.17.0.3:80/ on container 7.0-app-run-132881182833026629
  Stack Trace:
     at Microsoft.DotNet.Docker.Tests.ImageScenarioVerifier.GetHttpResponseFromContainerAsync(String containerName, DockerHelper dockerHelper, ITestOutputHelper outputHelper, Int32 containerPort, String pathAndQuery, Action`1 validateCallback) in /repo/tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs:line 292
   at Microsoft.DotNet.Docker.Tests.ImageScenarioVerifier.VerifyHttpResponseFromContainerAsync(String containerName, DockerHelper dockerHelper, ITestOutputHelper outputHelper, Int32 containerPort, String pathAndQuery) in /repo/tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs:line 297
   at Microsoft.DotNet.Docker.Tests.ImageScenarioVerifier.RunTestAppImage(String image, Boolean runAsAdmin, String command) in /repo/tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs:line 236
   at Microsoft.DotNet.Docker.Tests.ImageScenarioVerifier.Execute() in /repo/tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs:line 59
   at Microsoft.DotNet.Docker.Tests.AspnetImageTests.VerifyAppScenario(ProductImageData imageData) in /repo/tests/Microsoft.DotNet.Docker.Tests/AspnetImageTests.cs:line 28
--- End of stack trace from previous location ---
```

**Comment by mthalman** [comment]
I've identified the root cause of this issue.

Here's the error that occurs when attempting to start the aspnet container:

```
Unhandled exception. System.Net.Sockets.SocketException (13): Permission denied
at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
at System.Net.Sockets.Socket.Bind(EndPoint localEP)
at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
at Microsoft.AspNetCore.Builder.WebApplication.Run(String url)
at Program.<Main>$(String[] args) in /app/Program.cs:line 6
```

It was found that running the container as the root user caused it to start successfully. That explains why it was only distroless containers having this issue because a non-root user is only used for distroless.

I suspected that the Docker daemon may be the issue here. The version of Docker installed in the Build.Ubuntu.1804.Amd64 VM image used by this agent pool is 19.03.8. After installing the latest version, 20.10.9, and targeting that version instead, I was able to successfully run the container. So it appears that this was some bug in the Docker daemon that has since been resolved. We should get the Docker version upgraded in this VM image.

**Comment by mthalman** [comment]
Tests can be re-enabled now that https://github.com/dotnet/core-eng/issues/15492 is fixed.

**Comment by mthalman** [comment]
This issue has cropped up again, this time for public builds. This is strange because it was thought that the Docker version was causing this. But the agents have Docker version 20.10.11.
