### ISSUE TITLE
dotnet/samples:aspnetapp missing Armv8 image

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-docker#3859]
It fails on Apple M1 due to that (due to not working under QEMU).

```bash
rich@MacBook-Air aspnetapp % docker run --rm -it -p 8000:80 mcr.microsoft.com/dotnet/samples:aspnetapp
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Unhandled exception. System.IO.IOException: Function not implemented
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
```

**Comment by mthalman** [comment]
This doesn't make sense to me. The manifest for that tag does have an entry for Linux Arm64. Is there perhaps a bug with Docker?

```console
$ docker manifest inspect mcr.microsoft.com/dotnet/samples:aspnetapp
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1788,
         "digest": "sha256:aef35f623d33e8e0d69a1cff8f26d557557cc7ef4a38eca4a96634515b0ef174",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1788,
         "digest": "sha256:a72a7589a4db897917e16536579fc594257bb792d0209d44dc5feba6592730dc",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1788,
         "digest": "sha256:0539ac06a2168fdf60b2e692ed227114e53935f33e8f96b40f40853e6f824dd5",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2801,
         "digest": "sha256:b600a9a1ba30b0bc6643e42a2ea00d5d5348f141c71370ecca92ce559d166987",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.17763.3046"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2801,
         "digest": "sha256:069b6bc5e5e776cc6b9f92dc265e14305f26417b79b9e5acb8bb5e2abfca2fab",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.19042.1766"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2801,
         "digest": "sha256:2c55b73190a12bf5c56273a02cfe6d76b8af519e792d5dde0df7fbab8133941b",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.20348.768"
         }
      }
   ]
}
```

**Comment by mthalman** [comment]
FWIW, I don't see this behavior on my M1.

```console
thalman@Matts-MacBook-Pro dotnetapp % docker run --rm -it -p 8000:80 mcr.microsoft.com/dotnet/samples:aspnetapp
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {c845909a-c58a-4b17-8f25-24073e95438f} may be persisted to storage in unencrypted form.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:80
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app/
```

```console
thalman@Matts-MacBook-Pro dotnetapp % docker run --rm -it -p 8000:80 mcr.microsoft.com/dotnet/samples:dotnetapp
Unable to find image 'mcr.microsoft.com/dotnet/samples:dotnetapp' locally
dotnetapp: Pulling from dotnet/samples
dc1f00a5d701: Already exists 
1f33e89d5ee1: Already exists 
b816976f7223: Already exists 
ceafe474c22e: Already exists 
5f25881fbb61: Pull complete 
8507c8b4ddc4: Pull complete 
Digest: sha256:a4832fed0100fcc875a3c3770bb1aac6f21384b9a78ba0eb76f4a8b0b822134c
Status: Downloaded newer image for mcr.microsoft.com/dotnet/samples:dotnetapp
         42
         42              ,d                             ,d
         42              42                             42
 ,adPPYb,42  ,adPPYba, MM42MMM 8b,dPPYba,   ,adPPYba, MM42MMM
a8"    `Y42 a8"     "8a  42    42P'   `"8a a8P_____42   42
8b       42 8b       d8  42    42       42 8PP"""""""   42
"8a,   ,d42 "8a,   ,a8"  42,   42       42 "8b,   ,aa   42,
 `"8bbdP"Y8  `"YbbdP"'   "Y428 42       42  `"Ybbd8"'   "Y428

.NET 6.0.6
Debian GNU/Linux 11 (bullseye)

OSArchitecture: Arm64
ProcessorCount: 4
TotalAvailableMemoryBytes: 7.76 GiB
```

**Comment by richlander** [comment]
Very odd. Must have been a gremlin on my side. I think I somehow had bad content for that tag. I pulled and then ran and it now works. Sorry about that.

**Comment by cecilphillip** [comment]
@richlander hhhmm the .NET 6.0 tagged images always resolve to amd64 on my M1 machine. I get that same error you were getting. I did a `docker system prune`, pulled the image again, it still resolves to amd64.

<img width="863" alt="Screen Shot 2022-07-23 at 2 50 04 AM" src="https://user-images.githubusercontent.com/350882/180594051-ac83e434-a39d-4c70-9a53-75b252278b53.png">

**Comment by richlander** [comment]
Ya, as long as you don't set the platform explicitly, you'll get Arm64 images. It can be very confusing since there is only one namespace for images.
