### ISSUE TITLE
aspnetcore:60

### ISSUE THREAD

**Issue by jchhca** [dotnet/dotnet-docker#3903]
### Describe the Bug

Noticed today error on new API deployments using mcr.microsoft.com/dotnet/aspnet:6.0 base image to OpenShift 4.9. 

**All HTTP requests are failing:**

Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMIUL1796VND", Request id "0HMIUL1796VND:00000002": An unhandled exception was thrown by the application.
      System.TypeInitializationException: The type initializer for 'Dynatrace.OneAgent.StringTracking.StringTrackingApi' threw an exception.
       ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
         at Dynatrace.OneAgent.StringTracking.Storage.I.CheckedStringTrackingStore..ctor()
         at Dynatrace.OneAgent.StringTracking.StringTrackingApi..cctor()
         --- End of inner exception stack trace ---
         at Dynatrace.OneAgent.StringTracking.StringTrackingApi.NewSource(SourceConfig& config)
         at Dynatrace.OneAgent.Introspection.Shared.NewAspNetCoreTracingMiddlewareBase`1.InvokeAspMethod(Context context, IHttpContext requestContext)
         at Dynatrace.OneAgent.Introspection.Shared.NewAspNetCoreTracingMiddlewareBase`1.Invoke(Context context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

Same code worked fine when deployed last week and previously

OpenShift v4.9
Kubernetes v1.22.8+f34b40c
ASP.NET Core 6.0

### Steps to Reproduce

All HTTP request fail with the above error.

Docker file:

FROM mcr.microsoft.com/dotnet/aspnet:6.0

WORKDIR /app
COPY . .

ENV ASPNETCORE_URLS=http://*:8080

EXPOSE 8080

ENTRYPOINT ["dotnet", "Api.dll"]

OpenShift Deployment YAML:

apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: Api Template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: ${{REPLICA_COUNT}}
    revisionHistoryLimit: 10
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 0%
        maxUnavailable: 100%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
      spec:
        containers:
        - env:
          - name: App__Version
            value: ${APPLICATION_VERSION}
          - name: Cosmos__CosmosUrl
            value: ${COSMOS_URL}
          - name: Cosmos__CosmosKey
            value: ${COSMOS_KEY}
          - name: Cosmos__ProxyUrl
            value: ${COSMOS_PROXY_URL}
          - name: Scheduler__MultiTenancy
            value: ${SCHEDULER_MULTITENANCY}
          - name: Scheduler__Environment
            value: ${SCHEDULER_ENVIRONMENT}
          - name: Scheduler__Tenants
            value: ${TENANTS}
          - name: APPINSIGHTS_INSTRUMENTATIONKEY
            value: ${APPINSIGHTS_INSTRUMENTATION_KEY}
          - name: Api__IdpUrl
            value: ${API_IDP_URL}
          - name: Api__SignalRConnectionString
            value: ${API_SIGNALR_CONNECTION_STRING}
          - name: Api__EnableSwagger
            value: ${API_ENABLE_SWAGGER}
          - name: Api__Brokers
            value: ${API_BROKERS}
          - name: Api__NotificationTopic
            value: ${API_NOTIFICATIONTOPIC}
          - name: Api__SaslKerberosPrincipal
            value: ${API_KERBEROSPRINCIPAL}
          - name: Logging__LogLevel__Default
            value: ${API_LOGGING_LEVEL}
          image: image-registry.openshift-image-registry.svc:5000/${PROJECT_NAME}/${APPLICATION_NAME}:${TAG}
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          resources:
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}  
            limits:
              memory: ${MEMORY_LIMIT}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Route
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    host: ${APPLICATION_HOSTNAME}
    to:
      kind: "Service"
      name: ${APPLICATION_NAME}
    tls:
      termination: edge
- apiVersion: v1
  kind: Service
  metadata: 
    name: ${APPLICATION_NAME}
    annotations:
      description: Exposes and load balances the application pods
  spec:
    ports:
    - name: ${APPLICATION_NAME}-http
      port: 443
      targetPort: 8080
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}  
parameters:
- description: The name for the application.
  displayName: Application Name
  name: APPLICATION_NAME
  required: true
- description: Custom hostname for service routes.  Leave blank for default hostname. e.g. <application-name>.<project>.<default-domain-suffix>'
  displayName: Application Hostname
  name: APPLICATION_HOSTNAME
- description: The application project.
  displayName: Project Name
  name: PROJECT_NAME
  required: true
- description: The container tag to deploy
  displayName: Tag
  name: TAG
  required: true
- description: Appsetting application version
  displayName:  Application Version
  name: APPLICATION_VERSION
- description: Appsetting cosmos url 
  displayName: Cosmos Url
  name: COSMOS_URL
  required: true
- description: Appsetting cosmos key
  displayName: Cosmos Key
  name: COSMOS_KEY
  required: true
- description: Appsetting cosmos proxy url
  displayName: Cosmos Proxy Url
  name: COSMOS_PROXY_URL
  required: false
- description: Appsetting scheduler multitenancy
  displayName: Scheduler MultiTenancy
  name: SCHEDULER_MULTITENANCY
  required: true
- description: Appsetting scheduler environment
  displayName: Scheduler Environment
  name: SCHEDULER_ENVIRONMENT
  required: true
- description: Appsetting tenants
  displayName: Tenants
  name: TENANTS
  required: false
- description: Appsetting appinsights key
  displayName:  AppInsights Key
  name: APPINSIGHTS_INSTRUMENTATION_KEY
  required: true
- description: Appsetting api idp url
  displayName:  Api IDP Url
  name: API_IDP_URL
  required: true
- description: Appsetting api signalr connection string
  displayName:  Api SignalR Connection string
  name: API_SIGNALR_CONNECTION_STRING
  required: true
- description: Appsetting api enable swagger
  displayName:  Api Enable Swagger
  name: API_ENABLE_SWAGGER
  required: true
- description: Appsetting api logging level
  displayName:  Api Logging Level
  name: API_LOGGING_LEVEL
  required: true
- description: Appsetting brokers
  displayName: Api Brokers
  name: API_BROKERS
  required: true
- description: Appsetting topic
  displayName: Api Topic
  name: API_NOTIFICATIONTOPIC
  required: true
- description: Appsetting kerberos prinicpal
  displayName: Api Kerberos Prinicpal
  name: API_KERBEROSPRINCIPAL
  required: true
- description: Requested amount of memory needed to run the container under normal conditions.
  displayName: Memory Request
  name: MEMORY_REQUEST
  required: true
  value: 256Mi
- description: Limit amount of memory that can be requested by the container.
  displayName: Memory Request
  name: MEMORY_LIMIT
  required: true
  value: 512Mi
- description: Requested amount of CPU needed to run the container under normal conditions. (in millicores, 100 millicores = .1 core)
  displayName: CPU Request
  name: CPU_REQUEST
  required: true
  value: 200m
- description: Requested Replicas
  displayName: Replica Request
  name: REPLICA_COUNT
  required: true

**Comment by richlander** [comment]
Can you try using a more specific tag? I'm assuming you are using `6.0.6` currently (which you can validate). Can you try a `6.0.5` tag? That would help us validate if the change was in `6.0.6`. If you see the same behavior on earlier `6.0` versions, then the issue must be elsewhere.

**Comment by richlander** [comment]
Please report back if this is still an issue.
