### ISSUE TITLE
System.UnauthorizedAccessException: Access to the path '/proc/1/map_files' is denied. 

### ISSUE THREAD

**Issue by tangbao0002** [dotnet/dotnet-docker#3973]
In my conputer, the docker information is as the following:

```
> [root@localhost /]# **docker info**
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

>Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 17
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.21.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.795GiB
 Name: localhost.localdomain
 ID: TSA4:3GYJ:B6AK:OWNO:M3A2:B63X:JPAF:63WM:2KXQ:AQSU:ROQZ:GPPZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**My dockerfile is as the following:**

```Dockerfile
#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["web.csproj", "."]
RUN dotnet restore "./web.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "web.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "web.dll"]
```

**And the error is as the following:**
```
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/proc/1/map_files' is denied.
 ---> System.IO.IOException: Operation not permitted
   --- End of inner exception stack trace ---
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry(Byte* entryBufferPtr, Int32 bufferLength)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance..ctor(FileSystemWatcher watcher, SafeFileHandle inotifyHandle, String directoryPath, Boolean includeSubdirectories, NotifyFilters notifyFilters, CancellationToken cancellationToken)
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationExtensions.Add[TSource](IConfigurationBuilder builder, Action`1 configureSource)
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, IFileProvider provider, String path, Boolean optional, Boolean reloadOnChange)
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, String path, Boolean optional, Boolean reloadOnChange)
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass11_0.<ConfigureDefaults>b__1(HostBuilderContext hostingContext, IConfigurationBuilder config)
   at Microsoft.AspNetCore.Hosting.BootstrapHostBuilder.RunDefaultCallbacks(ConfigurationManager configuration, HostBuilder innerBuilder)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(String[] args)
   at Program.<Main>$(String[] args) in /src/Program.cs:line 1
```

**Comment by tbluesky2012** [comment]
![image](https://user-images.githubusercontent.com/12482184/183542008-ef7dc73a-1b6c-4392-8b5e-2dacfc17323a.png)
 
**I runned the container by using 'docker run -p 9000:80 mywebapp'**

**Comment by tbluesky2012** [comment]
I runned the container by using 'docker run -p 9000:80 mywebapp'





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dotnet/dotnet-docker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月8日(星期一) 晚上9:51
***@***.***&gt;;
抄送:&nbsp;"Blue ***@***.******@***.***&gt;;
主题:&nbsp;Re: [dotnet/dotnet-docker] System.UnauthorizedAccessException: Access to the path '/proc/1/map_files' is denied.  (Issue #3973)





 
What command are you using to run the container?

**Comment by richlander** [comment]
What app are you running?

Not quite the same, but I notice this problem on my Synology. I've been meeting to update the sample to avoid this.

```bash
rich@kamloops:~$ docker run --rm mcr.microsoft.com/dotnet/samples
Unable to find image 'mcr.microsoft.com/dotnet/samples:latest' locally
latest: Pulling from dotnet/samples
Digest: sha256:c1e940eb88977f20266a61a9c036853e3a7a413019474da45b7023a1e0bf7916
Status: Downloaded newer image for mcr.microsoft.com/dotnet/samples:latest
         42
         42              ,d                             ,d
         42              42                             42
 ,adPPYb,42  ,adPPYba, MM42MMM 8b,dPPYba,   ,adPPYba, MM42MMM
a8"    `Y42 a8"     "8a  42    42P'   `"8a a8P_____42   42
8b       42 8b       d8  42    42       42 8PP"""""""   42
"8a,   ,d42 "8a,   ,a8"  42,   42       42 "8b,   ,aa   42,
 `"8bbdP"Y8  `"YbbdP"'   "Y428 42       42  `"Ybbd8"'   "Y428

.NET 6.0.7
Debian GNU/Linux 11 (bullseye)

OSArchitecture: X64
ProcessorCount: 8
TotalAvailableMemoryBytes: 7.54 GiB
Unhandled exception. System.IO.FileNotFoundException: Could not find file '/sys/fs/cgroup/cpu/cpu.cfs_quota_us'.
File name: '/sys/fs/cgroup/cpu/cpu.cfs_quota_us'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at System.IO.File.ReadAllLines(String path)
   at Program.<Main>$(String[] args) in /source/Program.cs:line 61
```

**Comment by tbluesky2012** [comment]
Thanks for your reply,
My app is a simple test project developed with .Net 6,&nbsp; And&nbsp;the attachment is the source code.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dotnet/dotnet-docker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月9日(星期二) 上午9:33
***@***.***&gt;;
抄送:&nbsp;"Blue ***@***.******@***.***&gt;;
主题:&nbsp;Re: [dotnet/dotnet-docker] System.UnauthorizedAccessException: Access to the path '/proc/1/map_files' is denied.  (Issue #3973)





 
What app are you running?
 
Not quite the same, but I notice this problem on my Synology. I've been meeting to update the sample to avoid this.
 ***@***.***:~$ docker run --rm mcr.microsoft.com/dotnet/samples Unable to find image 'mcr.microsoft.com/dotnet/samples:latest' locally latest: Pulling from dotnet/samples Digest: sha256:c1e940eb88977f20266a61a9c036853e3a7a413019474da45b7023a1e0bf7916 Status: Downloaded newer image for mcr.microsoft.com/dotnet/samples:latest          42          42              ,d                             ,d          42              42                             42  ,adPPYb,42  ,adPPYba, MM42MMM 8b,dPPYba,   ,adPPYba, MM42MMM a8"    `Y42 a8"     "8a  42    42P'   `"8a a8P_____42   42 8b       42 8b       d8  42    42       42 8PP"""""""   42 "8a,   ,d42 "8a,   ,a8"  42,   42       42 "8b,   ,aa   42,  `"8bbdP"Y8  `"YbbdP"'   "Y428 42       42  `"Ybbd8"'   "Y428  .NET 6.0.7 Debian GNU/Linux 11 (bullseye)  OSArchitecture: X64 ProcessorCount: 8 TotalAvailableMemoryBytes: 7.54 GiB Unhandled exception. System.IO.FileNotFoundException: Could not find file '/sys/fs/cgroup/cpu/cpu.cfs_quota_us'. File name: '/sys/fs/cgroup/cpu/cpu.cfs_quota_us'    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)    at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)    at System.IO.File.InternalReadAllLines(String path, Encoding encoding)    at System.IO.File.ReadAllLines(String path)    at Program.<Main&gt;$(String[] args) in /source/Program.cs:line 61

**Comment by richlander** [comment]
Can you post that as a gist or something? I don't think GitHub email support attachments. Also, replying by email is never great and should generally be avoided.

**Comment by tbluesky2012** [comment]
Thanks for your reply,
My app is a simple test project developed with .Net 6,  And the attachment is the source code.
[web.zip](https://github.com/dotnet/dotnet-docker/files/9287056/web.zip)
