### ISSUE TITLE
aspnet:6.0-alpine cause OpenSSL error in Linux (AWS)

### ISSUE THREAD

**Issue by NguyenCu** [dotnet/dotnet-docker#3976]
### Describe the Bug

We have a few APIs built with netcoreapp3.1 framework and they all are running well in AWS Linux containers with sdk:3.1-alpine.
`FROM mcr.docker.internal.cba/dotnet/core/sdk:3.1-alpine AS build`

Recently, we have upgraded our APIs to use dotnet6.0 framework (with **aspnet:6.0-alpine**). We started to see OpenSSL errors consistently happened, sample error below.
`FROM mcr.docker.internal.cba/dotnet/sdk:6.0-alpine AS build`

### Workarounds

When we roll them back to netcoreapp3.1/sdk:3.1-alpine, every thing works fine.
We also tried using dotnet5.0 (obsolete) and dotnet7.0 (in preview), every thing works fine, no OpenSSL Error found.

### Steps to Reproduce

Only when we change them back to dotnet6.0, OpenSSL errors start to occur.

### The errors
The errors vary with different messages
- data too large for modulus
- last (or first) octet invalid
- salt length recovery failed

```
"Exception": "System.Net.Http.HttpRequestException: Error while copying content to a stream.
    ---> System.IO.IOException: The decryption operation failed, see inner exception.
    ---> Interop+OpenSsl+SslException: Decrypt failed with OpenSSL error - SSL_ERROR_SSL.
    ---> Interop+Crypto+OpenSslCryptographicException: error:04067084:rsa routines:rsa_ossl_public_decrypt:data too large for modulus
      --- End of inner exception stack trace ---
      at Interop.OpenSsl.Decrypt(SafeSslHandle context, Span`1 buffer, SslErrorCode& errorCode)
      at System.Net.Security.SslStreamPal.DecryptMessage(SafeDeleteSslContext securityContext, Span`1 buffer, Int32& offset, Int32& count)
      --- End of inner exception stack trace ---
      at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
      at System.Net.Http.HttpConnection.FillAsync(Boolean async)
      at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
      at System.Net.Http.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
      at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
      --- End of inner exception stack trace ---
      at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
      at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
```

### dotnet info in one container

```
/app $ dotnet --info

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
Any ideas? Many thanks.

**Comment by mthalman** [comment]
Are you able to provide a repro project that demonstrates this error at all?

**Comment by mthalman** [comment]
@NguyenCu - Are you able to provide repro steps for this?

**Comment by mthalman** [comment]
This is a stale issue and 6.0 is EOL. Closing.
