### ISSUE TITLE
tzdata missing in aspnet:7.0-jammy-arm64v8

### ISSUE THREAD

**Issue by christallire** [dotnet/dotnet-docker#4201]
### Describe the Bug

tzdata is missing in `aspnet:7.0-jammy-arm64v8`
I was using just fine with 6.0 image.
Haven't had a time to check other images.

```TimeZoneNotFoundException, Message: The time zone ID 'Asia/Seoul' was not found on the local computer.
Meta:
  InnerMessages: Could not find a part of the path '/usr/share/zoneinfo/Asia/Seoul'.
Server StackTrace:
 System.TimeZoneNotFoundException: The time zone ID 'Asia/Seoul' was not found on the local computer.
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/usr/share/zoneinfo/Asia/Seoul'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.File.ReadAllBytes(String path)
   at System.TimeZoneInfo.TryGetTimeZoneFromLocalMachineCore(String id, TimeZoneInfo& value, Exception& e)
   --- End of inner exception stack trace ---
   at System.TimeZoneInfo.FindSystemTimeZoneById(String id)
```

### Steps to Reproduce

```
# kubectl exec -it order-service-8f464b8c6-jvxzt -c app -- /bin/bash
root@order-service-8f464b8c6-jvxzt:~# apt list sed
Listing... Done
sed/now 4.8-1ubuntu2 arm64 [installed,local]
root@order-service-8f464b8c6-jvxzt:~# apt list tzdata
Listing... Done
root@order-service-8f464b8c6-jvxzt:/app# cat /usr/share/zoneinfo/Asia/Seoul
cat: /usr/share/zoneinfo/Asia/Seoul: No such file or directory
```

### Output of `kubectl version`

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.13", GitCommit:"a43c0904d0de10f92aa3956c74489c45e6453d6e", GitTreeState:"clean", BuildDate:"2022-08-17T18:28:56Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.13-eks-fb459a0", GitCommit:"55bd5d5cb7d32bc35e4e050f536181196fb8c6f7", GitTreeState:"clean", BuildDate:"2022-10-24T20:35:40Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by mthalman** [comment]
The `tzdata` package is not a package that .NET installs, or guarantees to be installed. Its presence is purely dictated by the base Linux image. The Ubuntu 22.04 (Jammy) base image no longer includes `tzdata` like they did with Ubuntu 20.04 (Focal). For example, the `6.0-jammy` tag also did not include `tzdata`.

Your Dockerfile here is a bit confusing though:

> ```
> FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
> WORKDIR /src
> 
> RUN apt-get update && DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
> ```

It should not be necessary to install `tzdata` in that case because you're using just the `7.0` tag with no OS specified. So by default, you're getting Debian 11 which does have `tzdata` installed.

But for any .NET version, if you're using Ubuntu 22.04 (Jammy), then yes you'll need to explicitly install `tzdata` yourself.

**Comment by christallire** [comment]
> The `tzdata` package is not a package that .NET installs, or guarantees to be installed. Its presence is purely dictated by the base Linux image. The Ubuntu 22.04 (Jammy) base image no longer includes `tzdata` like they did with Ubuntu 20.04 (Focal). For example, the `6.0-jammy` tag also did not include `tzdata`.
> 
> Your Dockerfile here is a bit confusing though:
> 
> > ```
> > FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
> > WORKDIR /src
> > 
> > RUN apt-get update && DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
> > ```
> 
> It should not be necessary to install `tzdata` in that case because you're using just the `7.0` tag with no OS specified. So by default, you're getting Debian 11 (Bullseye) which does have `tzdata` installed.
> 
> But for any .NET version, if you're using Ubuntu 22.04 (Jammy), then yes you'll need to explicitly install `tzdata` yourself.

That's because there are no github arm64 runners and I had no choice but to include THAT into the build image, and I thought that wouldn't do any damage.
and would it be nice to have no difference when you upgrade it to .net 7 rather than search google and "oh it's upstream's problem. I have to fix my docker script for 'jammy' installation because there's no 'focal' image for .net7".

**Comment by RogerSep** [comment]
Not including `tzdata` kind of breaks the standard library.

For example:
```
TimeZoneInfo.ConvertTimeBySystemTimeZoneId(result, "US/Pacific")
```

Results in exception:
```
The time zone ID 'US/Pacific' was not found on the local computer.
```

I'm happy to make a PR if some guidance is provided as to what's the philosophy on these cases. I feel like it should be maintained by the official microsoft images as it's part of the core lib.

**Comment by richlander** [comment]
@tarekgh -- Can you offer some thoughts on this?

**Comment by tarekgh** [comment]
> This gets back to (kinda) Globalization Invariant Mode. IMO, our regular images should be full-featured w/rt to globalization. Does that meet your expecation?

I am not seeing the time zones support is part of globalization and we shouldn't tie it to the Globalization mode. Date/Time is not directly connected to globalization except when formatting is involved. But retrieving or converting time, I think this should be supported regardless. 
What is the cost of adding tzdata to the image?

**Comment by RogerSep** [comment]
What does cost mean? it's 10MB in Alpine at least

**Comment by tarekgh** [comment]
> What does cost mean? it's 10MB in Alpine at least

Yes the size what I meant.

**Comment by richlander** [comment]
I wasn't trying to suggest that Date/Time is part of our globalization mode. I was suggesting it was very similar. Time zones are very clearly a "globalization feature" so I was asking what we should propose in terms enabling such features by default in our container images.

**Comment by richlander** [comment]
@tarekgh and I just discussed this. We concluded that our Debian and Ubuntu (non-Chisel) should always include ICU and tzdata.

**Comment by richlander** [comment]
We should document our policy on glob/world features in our principles doc.

**Comment by mthalman** [comment]
[Triage]
Without the tzdata package, it is still possible to make use of UTC time APIs. Our policy is to not include tzdata by default. In some cases, tzdata is available which comes from the base Linux image. But it is not our policy to ensure that exists as a general rule. There will be forthcoming guidance on how best to configure Dockerfiles to include tzdata.

**Comment by svrooij** [comment]
Others facing this issue, you can also mount the tzdata from the host system if you combine that with setting the `TZ` environment you can still use the time zone data. This docker compose is tested on Ubuntu host system.

```yaml
services:
  some_service:
    image: ....
    env:
      - .TZ=Europe/Amsterdam
    volumes:
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      - /etc/localtime:/etc/localtime:ro
```

**Comment by richlander** [comment]
Here's a doc on the topic: https://github.com/dotnet/dotnet-docker/blob/main/samples/enable-globalization.md

**Comment by svrooij** [comment]
@richlander I used my favorite search engine and ended up at this issue and not in the documentation. Mapping the time zone data from the host to the container might be an easier way, if you no longer create docker files but instead use the msbuild container target

**Comment by richlander** [comment]
Feel free to add that option to the doc.

We (meaning me) have done. a poor job increasingly the visibility of our docs. One of my next tasks is to rewrite the container docs in the official .NET docs and link to this doc set. That should help with SEO.

**Comment by mthalman** [comment]
Mapping from the host is going to be one of those things that won't work for everybody. It makes containers less "portable" and more dependent on the configuration of the host which can be troublesome in the context of machines in the cloud where you may not have influence over the configuration.
