### ISSUE TITLE
.Net 6 Distroless Mariner2.0 image has no libicu installed

### ISSUE THREAD

**Issue by Vacant0mens** [dotnet/dotnet-docker#4671]
### Describe the Bug

When running an application that utilizes EntityFramework Core for SQLServer, it would seem that when connecting to the SQL server the localization/globalization isn't getting handled properly.

Most of the time, a good resolution to most ICU issues is to force invariant mode via environment variables (e.g. `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true`) and/or applying the setting during build in the .csproj file or in the msbuild parameters.

**_However_**, when globalization invariant is enabled, the code gets to EntityFramework attempting to connect to SQL for running migrations, but then throws this error:
```
 An error occurred starting the application
System.AggregateException: One or more errors occurred. (Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en-us is an invalid culture identifier.)
 ---> System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en-us is an invalid culture identifier.
   at System.Globalization.CultureInfo.GetCultureInfo(String name)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass31_0`2.<Execute>b__0(DbContext context, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation, Func`2 verifySucceeded)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists(Boolean retryOnNotExists)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
```
but with globalization invariant disabled, instead it crashes almost immediately with this:
```
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CachedCulturesByName()
   at System.Globalization.CultureInfo.GetCultureInfo(System.String)
   at System.Reflection.RuntimeAssembly.GetLocale()
   at System.Reflection.RuntimeAssembly.GetName(Boolean)
   at System.Reflection.Assembly.GetName()
   at Microsoft.Extensions.Hosting.HostBuilder.CreateHostingEnvironment()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
```

### Steps to Reproduce
1. create a project based on DotNet 6.0 that uses EntityFrameworkCore for SQLServer
2. In a dockerfile:
``` dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0 as base
RUN dotnet publish [projectname].csproj --self-contained=true -o /app --runtime=linux-x64
FROM mcr.microsoft.com/.dotnet/runtime:6.0-cbl-mariner2.0-distroless-amd64
# ironically, the `runtime-deps` and `aspnet` variants have the same issues
WORKDIR /app
COPY --from=base /app /app
CMD [ "./[projectname]" ]
```
3. `docker build -t myproject`
4.  `docker run -ti --rm -e DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=[true|false] myproject`
5. running the final command with `true` or `false` will give you the first and second errors above, respectively. (If you don't add any migrations, I'm not sure, but I would expect that you'd get a similar error as soon as you made your first call to the database).

### Proposed solutions
1. Add the ICULIB package to the [distroless dockerfile](https://github.com/dotnet/dotnet-docker/blob/main/src/runtime/6.0/cbl-mariner2.0-distroless/amd64/Dockerfile), since it's a requirement for many things to work properly with DotNet 6 on Linux.
OR
2. Create a variant of the distroless images that contains the iculib package (i.e. `dotnet/runtime-icu:6.0-cbl-mariner2.0-distroless-amd64`)

### Other Information
I'm running a bone-stock version of Docker Desktop on Windows, freshly installed and updated last week. No extensions added, no preferences changed.

**Comment by lbussell** [comment]
Hi @Vacant0mens,

ICU libraries are excluded from our distroless images intentionally to keep size down. All of our distroless and Alpine images have globalization invariant mode enabled by default (See https://github.com/dotnet/dotnet-docker/issues/3394 for context). We have a localization sample [here](https://github.com/dotnet/dotnet-docker/blob/main/samples/globalapp) which recommends using Alpine or Ubuntu non-distroless and installing extra icu packages yourself. Our jammy images also come [with `libicu70` installed](https://github.com/dotnet/dotnet-docker/blob/6018bcfcc9fe51c75bdddefed92bcf7e8ba70d16/src/runtime-deps/6.0/jammy/amd64/Dockerfile#L17).

If you think the first `System.Globalization.CultureNotFoundException` when globalization invariant mode is caused by a bug in efcore, you should open an issue there: https://github.com/dotnet/efcore

Additionally, CBL-Mariner container images are only supported for internal Microsoft use: https://mcr.microsoft.com/en-us/product/cbl-mariner/base/core/about

**Comment by mthalman** [comment]
This is related to https://github.com/dotnet/SqlClient/issues/220. That says it's by design so it doesn't look like this behavior will be changed. That means the default behavior with EF Core in Alpine and distroless containers will get this error. The solution to this is to ensure that the ICU library is installed in those environments. It's understood that there is some friction when attempting to do this in a distroless environment. But for now, we've determined that excluding ICU from the base images is the approach we want to use because of the size factor.
