### ISSUE TITLE
microsoft/dotnet:2.1-runtime do not open appsettings.json file

### ISSUE THREAD

**Issue by Itfly** [dotnet/dotnet-docker#491]
## Steps to reproduce the issue
1. Use `microsoft/dotnet:2.1-runtime` to build dotnet console app
2. The console app would read appsettings.json like below code:
```
                    var env = context.HostingEnvironment;
                    builder.SetBasePath(AppContext.BaseDirectory)
                    .AddJsonFile("appsettings.json", optional: false)
                    .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true);
```
3. And it works on visual studio or dotnet:latest, however it throws exception on 2.1-runtime:
```
write(9, "System.IO.FileNotFoundException:"..., 883System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is '/app/appsettings.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.RunConsoleAsync(IHostBuilder hostBuilder, CancellationToken cancellationToken)
   at Microsoft.AI.Words.Server.Program.Main(String[] args) in C:\workspace\Infrastructure\sample\wordsmith-demo\words\src\Words.Server\Program.cs:line 19
```
By using the `strace` tool, it seems dotnet do not open appsettings.json....

## Expected behavior
open appsettings.json before read

## Actual behavior
do not open appsettings.json

## Output of `docker version`

```
λ docker version
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:06:28 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:14:32 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

## Output of `dockerfile`
```
FROM microsoft/dotnet:2.1-runtime

WORKDIR /app
COPY bin/Release/Publish .

EXPOSE 8080

CMD ["dotnet", "Words.Server.dll"]
```

**Comment by MichaelSimons** [comment]
@Itfly - Is `appsettings.json` located in the `bin/Release/Publish` directory on your Docker host machine?  Have you verified the `appsettings.json` file is getting copied into your container?  To verify this you could run the following command `docker run --rm --entrypoint ls <your image name>`.  This should list out the contents of the current directory (e.g. /app).

**Comment by Itfly** [comment]
@MichaelSimons Yes, `appsettings.json` is in the docker image and running container. I think this is a bug in the dotnet:2.1-runtime since when i used dotnet:latest to build image and it works well. Also i used `strace` to trace the system calls there's no `open(/app/appsettings.json)` call before it throws exception:

```
munmap(0x7fe51400b000, 65536)           = 0
mmap(NULL, 65536, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe51400b000
mprotect(0x7fe51400b000, 65536, PROT_READ|PROT_WRITE) = 0
mprotect(0x7fe4a0652000, 4096, PROT_READ|PROT_WRITE) = 0
munmap(0x7fe51400b000, 65536)           = 0
flock(68, LOCK_UN)                      = 0
close(68)                               = 0
mmap(NULL, 65536, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe51400b000
mprotect(0x7fe51400b000, 65536, PROT_READ|PROT_WRITE) = 0
munmap(0x7fe51400b000, 65536)           = 0
mprotect(0x7fe4a0338000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7fe49f64d000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0x7fe49f64d000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
write(9, "System.IO.FileNotFoundException:"..., 883System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is '/app/appsettings.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.RunConsoleAsync(IHostBuilder hostBuilder, CancellationToken cancellationToken)
   at Microsoft.AI.Words.Server.Program.Main(String[] args) in C:\workspace\Infrastructure\sample\wordsmith-demo\words\src\Words.Server\Program.cs:line 19
   at Microsoft.AI.Words.Server.Program.<Main>(String[] args)) = 883
write(9, "\n", 1
)                       = 1
```

**Comment by MichaelSimons** [comment]
If that's the case, then this should be logged against the product (https://github.com/aspnet/Configuration/issues?) instead of the Docker images.

**Comment by Itfly** [comment]
@MichaelSimons Because My app works well on `dotnet:latest` (2.0), but gets exception on `dotnet:2.1-runtime`, also it works on my local machine (dotnet version is 2.1.104), so i think maybe it's a issue on  `dotnet:2.1-runtime`

**Comment by Itfly** [comment]
@MichaelSimons  Here's the info:
```
.NET Command Line Tools (2.1.104)

Product Information:
 Version:            2.1.104
 Commit SHA-1 hash:  48ec687460

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.104\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```

**Comment by MichaelSimons** [comment]
@Itfly - Can you provide a standalone repo that illustrates this issue.  I just tried my own sample and it worked as expected.  Thanks

**Comment by Itfly** [comment]
[TestAppSettings.zip](https://github.com/dotnet/dotnet-docker/files/1936556/TestAppSettings.zip)

**Comment by MichaelSimons** [comment]
This is not an issue specific to Docker.  I built and ran the attached `TestAppSettings` app on a physical ubuntu 16.04 machine (no Docker involved) and got the same exception.  The app works on a physical Windows machine and within a Windows container.  Closing issue in lieu of https://github.com/aspnet/Configuration/issues/814.
