### ISSUE TITLE
Public tests are affected by DockerHub rate-limiting when pulling `anchore/syft` for image content tests

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-docker#5724]
See [this test run ](https://dev.azure.com/dnceng-public/public/_build/results?buildId=753748&view=logs&j=a95e4578-4aa7-573a-6c67-8eb6060f8e97&t=141940a7-5483-5f13-4891-e8e98d971561&l=213)for example. I've copied the error output here:

```
[xUnit.net 00:15:07.10]     Microsoft.DotNet.Docker.Tests.AspnetImageTests.VerifyInstalledPackages(imageData: ProductImageData { Arch = Amd64, IsArm = False, OS = jammy-chiseled, IsDistroless = True, DefaultPort = 8080, NonRootUID = 1654, Platform = linux/amd64, ArchVariant = , IsWindows = False, Rid = linux-x64, OsVersion = , HasCustomSdk = True, GlobalizationInvariantMode = True, SdkOS = jammy, SdkImageVariant = None, OSTag = jammy-chiseled, OSDir = jammy-chiseled, Version = 8.0, VersionFamily = 8.0, ImageVariant = None, SupportedImageRepos = SDK, Runtime, Runtime_Deps, Aspnet, VersionString = 8.0 }) [FAIL]
  Failed Microsoft.DotNet.Docker.Tests.AspnetImageTests.VerifyInstalledPackages(imageData: ProductImageData { Arch = Amd64, IsArm = False, OS = jammy-chiseled, IsDistroless = True, DefaultPort = 8080, NonRootUID = 1654, Platform = linux/amd64, ArchVariant = , IsWindows = False, Rid = linux-x64, OsVersion = , HasCustomSdk = True, GlobalizationInvariantMode = True, SdkOS = jammy, SdkImageVariant = None, OSTag = jammy-chiseled, OSDir = jammy-chiseled, Version = 8.0, VersionFamily = 8.0, ImageVariant = None, SupportedImageRepos = SDK, Runtime, Runtime_Deps, Aspnet, VersionString = 8.0 }) [2 m 40 s]
  Error Message:
   System.InvalidOperationException : Failed to execute docker pull anchore/syft:v1.0.0
Exit code: 1
Standard Error: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
  Stack Trace:
     at Microsoft.DotNet.Docker.Tests.DockerHelper.Execute(String args, Boolean ignoreErrors, Boolean autoRetry, ITestOutputHelper outputHelper) in /repo/dotnet-docker/tests/Microsoft.DotNet.Docker.Tests/DockerHelper.cs:line 168
   at Microsoft.DotNet.Docker.Tests.DockerHelper.ExecuteWithLogging(String args, Boolean ignoreErrors, Boolean autoRetry) in /repo/dotnet-docker/tests/Microsoft.DotNet.Docker.Tests/DockerHelper.cs:line 183
   at Microsoft.DotNet.Docker.Tests.DockerHelper.Pull(String image) in /repo/dotnet-docker/tests/Microsoft.DotNet.Docker.Tests/DockerHelper.cs:line 260
   at Microsoft.DotNet.Docker.Tests.ProductImageTests.GetSyftOutput(String syftContainerName, ProductImageData imageData, DotNetImageRepo imageRepo, DockerHelper dockerHelper, IEnumerable`1 extraExcludePaths) in /repo/dotnet-docker/tests/Microsoft.DotNet.Docker.Tests/ProductImageTests.cs:line 292
   at Microsoft.DotNet.Docker.Tests.ProductImageTests.GetInstalledPackages(ProductImageData imageData, DotNetImageRepo imageRepo, DockerHelper dockerHelper, IEnumerable`1 extraExcludePaths) in /repo/dotnet-docker/tests/Microsoft.DotNet.Docker.Tests/ProductImageTests.cs:line 270
   at Microsoft.DotNet.Docker.Tests.ProductImageTests.VerifyInstalledPackagesBase(ProductImageData imageData, DotNetImageRepo imageRepo, DockerHelper dockerHelper, ITestOutputHelper outputHelper, IEnumerable`1 extraExcludePaths) in /repo/dotnet-docker/tests/Microsoft.DotNet.Docker.Tests/ProductImageTests.cs:line 232
   at Microsoft.DotNet.Docker.Tests.AspnetImageTests.VerifyInstalledPackages(ProductImageData imageData) in /repo/dotnet-docker/tests/Microsoft.DotNet.Docker.Tests/AspnetImageTests.cs:line 71
   at InvokeStub_AspnetImageTests.VerifyInstalledPackages(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
  Standard Output Messages:
 Executing: docker pull anchore/syft:v1.0.0
 Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

```

**Comment by lbussell** [comment]
This is mitigated by https://github.com/dotnet/dotnet-docker/pull/5725
