### ISSUE TITLE
9.0 SDK content tests are failing

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-docker#6007]
Example failing public PR validation run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=852014&view=logs&j=476b3909-b3ca-5c71-af60-d4d5b7c518c4&t=d904e5fa-7299-560b-0425-9e2025bd0f78

```
[xUnit.net 00:04:07.21]     Microsoft.DotNet.Docker.Tests.SdkImageTests.VerifyDotnetFolderContents(imageData: ProductImageData { Arch = Amd64, IsArm = False, OS = azurelinux3.0, IsDistroless = False, DefaultPort = 8080, NonRootUID = 1654, Platform = linux/amd64, ArchVariant = , IsWindows = False, Rid = linux-x64, OsVersion = 3.0, HasCustomSdk = False, GlobalizationInvariantMode = False, SdkOS = azurelinux3.0, SdkImageVariant = None, OSTag = azurelinux3.0, OSDir = azurelinux3.0, Version = 9.0, VersionFamily = 9.0, ImageVariant = None, SupportedImageRepos = SDK, Runtime, Runtime_Deps, Aspnet, VersionString = 9.0 }) [FAIL]
  Failed Microsoft.DotNet.Docker.Tests.SdkImageTests.VerifyDotnetFolderContents(imageData: ProductImageData { Arch = Amd64, IsArm = False, OS = azurelinux3.0, IsDistroless = False, DefaultPort = 8080, NonRootUID = 1654, Platform = linux/amd64, ArchVariant = , IsWindows = False, Rid = linux-x64, OsVersion = 3.0, HasCustomSdk = False, GlobalizationInvariantMode = False, SdkOS = azurelinux3.0, SdkImageVariant = None, OSTag = azurelinux3.0, OSDir = azurelinux3.0, Version = 9.0, VersionFamily = 9.0, ImageVariant = None, SupportedImageRepos = SDK, Runtime, Runtime_Deps, Aspnet, VersionString = 9.0 }) [16 s]
  Error Message:
   System.Net.Http.HttpRequestException : Response status code does not indicate success: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.).
  Stack Trace:
     at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.DotNet.Docker.Tests.HttpClientExtensions.DownloadFileAsync(HttpClient client, Uri uri, String path) in /repo/dotnet-docker/tests/Microsoft.DotNet.Docker.Tests/HttpClientExtensions.cs:line 15
   at Microsoft.DotNet.Docker.Tests.SdkImageTests.GetExpectedSdkContentsAsync(ProductImageData imageData) in /repo/dotnet-docker/tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs:line 332
   at Microsoft.DotNet.Docker.Tests.SdkImageTests.VerifyDotnetFolderContents(ProductImageData imageData) in /repo/dotnet-docker/tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs:line 166
--- End of stack trace from previous location ---

```

**Comment by lbussell** [comment]
Fixed with https://github.com/dotnet/dotnet-docker/pull/6009
