### ISSUE TITLE
2.1-sdk fails with BadImageFormatException

### ISSUE THREAD

**Issue by staff0rd** [dotnet/dotnet-docker#764]
## Steps to reproduce the issue
1. `docker run -it microsoft/dotnet:2.1-sdk dotnet --info`

## Expected behavior
A non-failing response

## Actual behavior
```bash
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The module was expected to contain an assembly manifest.
   at Microsoft.DotNet.Cli.MulticoreJitActivator.TryActivateMulticoreJit()
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

## Output of `docker version`

```
Docker version 18.06.1-ce, build e68fc7a
```

## Output of `docker info`

```
Containers: 14
 Running: 3
 Paused: 0
 Stopped: 11
Images: 33
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d183320
ID: QZLY:Q4TG:O4NK:FLSO:XOAC:R4SY:OQGL:J76Q:2IOP:RXDF:KKCH:NZ7L
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 47
 System Time: 2018-10-21T07:29:08.341412Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by MichaelSimons** [comment]
@staff0rd, could you please provide the full output for `docker version` as well as the digest of the image that reproduces the issue?

**Comment by MichaelSimons** [comment]
Closing because of no response to question.  Feel free you re-open if this is still an issue.  Please include the image digest that reproduces the issue.
