### ISSUE TITLE
Alpine aspnet 2.2.3 Couldn't find a valid ICU package installed on the system

### ISSUE THREAD

**Issue by imdocker** [dotnet/dotnet-docker#986]
## Steps to reproduce the issue
1. Use this Dockerfile
https://github.com/dotnet/dotnet-docker/blob/master/2.2/aspnet/alpine3.9/amd64/Dockerfile
or
https://github.com/dotnet/dotnet-docker/blob/master/2.2/aspnet/alpine3.8/amd64/Dockerfile
2. Add to Dockerfile
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
RUN apk add --no-cache icu-libs
3. Run application

## Expected behavior
Work, as old version, without error:
```
$echo $DOTNET_SYSTEM_GLOBALIZATION_INVARIANT
false
$ls -la /usr/bin/dotnet 
lrwxrwxrwx    1 root     root            24 Jan 15 13:32 /usr/bin/dotnet -> /usr/share/dotnet/dotnet
$dotnet --info

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

## Actual behavior
```
FailFast:
Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.

   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.AppDomain.InitializeCompatibilityFlags()
   at System.AppDomain.Setup(System.Object)
Aborted
$ls -la /usr/bin/dotnet 
lrwxrwxrwx    1 root     root            24 Mar 13 06:50 /usr/bin/dotnet -> /usr/share/dotnet/dotnet
$dotnet --info

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

## Output of `docker version`

```
Docker version 18.06.1-ce, build e68fc7a
```

## Output of `docker info`

```
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.14.4.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.796GiB
Security Options:
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by mthalman** [comment]
@imdocker - I'm unable to repro this.  Could you provide more details on what you're doing for step 3 "run application"?

In my repro attempt, I just used the sample ASP.NET Core project that exists at 
https://github.com/dotnet/dotnet-docker/tree/master/samples/aspnetapp.  I modified https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/Dockerfile.alpine-x64 to use Alpine 3.9 and include the env var and icu-libs:
```
# ...
# Include previous parts of the Dockerfile
# ...
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-alpine3.9 AS runtime
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
RUN apk add --no-cache icu-libs
WORKDIR /app
COPY --from=build /app/aspnetapp/out ./
ENTRYPOINT ["dotnet", "aspnetapp.dll"]
```

I then built the image with:
`docker build --pull -t aspnetapp -f Dockerfile.alpine-x64 .`

And then ran the app:
`docker run --name aspnetcore_sample --rm -it -p 8000:80 aspnetapp`

The app loaded fine in my browser.

If I run the container interactively with `docker run --name aspnetcore_sample --rm -it -p 8000:80 --entrypoint /bin/sh aspnetapp`, I see the same results as your Actual Behavior but with no error about the ICU package.  Running `dotnet aspnetapp.dll` works fine.

**Comment by imdocker** [comment]
@mthalman You can use my docker images for test:

[Hub docker](https://hub.docker.com/r/imdocker1/dotnet-core3/tags)
1) without icu error image with tag latest (version 2.2.1)
2) with error and builded from latest version with tag 008 (version 2.2.3) and it's this issue)
(This is autobuilds. And you can found sources files in github link from hub docker)

**Comment by mthalman** [comment]
@imdocker - That's not what I'm asking about.  The image you pointed me to is just the same thing as what exists in the Dockerfile at https://github.com/dotnet/dotnet-docker/blob/master/2.2/aspnet/alpine3.9/amd64/Dockerfile.  I'm asking what you're doing in step 3 to reproduce your issue.  Can you provide a set of simple steps?

**Comment by imdocker** [comment]
This commit and sources:
https://github.com/imdocker/dotnet-core3/commit/ee02218982f92f7e22e0feb8d6268f2c2f6cf584
autobuilded in docker hub with this tag:
```docker pull imdocker1/dotnet-core3:008```

You can reproduce bug with this image

**Comment by mthalman** [comment]
@imdocker  - You still haven't answered my question.  What specific steps are you taking with this image that cause the issue?  After I pull the image, what _specific_ steps should I take to repro your issue?  Feel free to reference the sample projects at https://github.com/dotnet/dotnet-docker/tree/master/samples as a test project.

**Comment by MichaelSimons** [comment]
Closing due to inactivity.  @imdocker - if this is still an issue for you, please provide exact steps that can be used to reproduce the issue.
